### ISSUE TITLE
Migrating from MWS

### ISSUE THREAD

**Issue by httphaul** [saleweaver/python-amazon-sp-api#10]
Is there an equivalent operation in SP-API for MWS's GetLowestOfferListingsForASIN?

I've been digging through the models and documentation and see no such function.

**Comment by saleweaver** [comment]
Do you mean this one? https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#get-productspricingv0itemsasinoffers

**Comment by httphaul** [comment]
> Do you mean this one? https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#get-productspricingv0itemsasinoffers

http://docs.developer.amazonservices.com/en_US/products/Products_GetLowestOfferListingsForASIN.html

That is similar but MWS allows 20 asins at once. I can't find any such animal in SP

**Comment by saleweaver** [comment]
GetPricing and GetCompetitivePricing both allow up to 20 Asins, I think what comes closest is competitive pricing. 

If you’re doing this for your own products, I’d use the notifications/subscriptions API instead though.

**Comment by httphaul** [comment]
CompetitivePricing is close but doesn't always return the lowest offer price.

Unfortunately it doesn't look like there's a direct replacement for GetLowestOfferListings unless I'm missing something.

(Not using on my own products)

**Comment by saleweaver** [comment]
I didn't have the scenario for my customers, so I don't know about a replacement then either. I guess you'll have to wait with the migration until such an endpoint is implemented.
