### ISSUE TITLE
{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}

### ISSUE THREAD

**Issue by Yvan8** [saleweaver/python-amazon-sp-api#1042]
**Which API - Endpoint is your request about.**

**Additional context**

**Comment by Yvan8** [comment]
{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''} 
怎么解决这个问题

**Comment by thinhnd2104** [comment]
You should calculate the number of requests per second base on the response headers `x-amzn-RateLimit-Limit`. Then create a pool to handle this error and try to request again if needed. For more information you can check [this one](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference).
