### ISSUE TITLE
Missing getListingOffersBatch endpoint

### ISSUE THREAD

**Issue by scotwk** [saleweaver/python-amazon-sp-api#1067]
**Which API - Endpoint is your request about.**

getListingOffersBatch endpoint is missing

https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#post-batchesproductspricingv0listingoffers

**Comment by scotwk** [comment]
I implemented this in #1070 - any thoughts?

**Comment by justinmcdaniel** [comment]
Came here to report this issue. I need this endpoint too, now that getItemOffersBatch has been significantly limited... any update on when this will be merged and live?
