### ISSUE TITLE
NameError: name 'ListingsItems' is not defined

### ISSUE THREAD

**Issue by AVazquezf** [saleweaver/python-amazon-sp-api#1082]
**Describe the bug**
I'm creating a Python program to use the Selling Partner API for Listings Items. I'm initially want to test the get_listings_item, so
then I can use the other API's delete_listings_item, patch_listings_item and put_listings_item.

The issue is that when calling ListingsItems class for the credentials from my Python program, I got the following error:
   NameError: name 'ListingsItems' is not defined

 The credentials are ok, because I used them in other Python programs calling the Catalog, Products and Reports API's and they run successfully.

My Python code is:

 # Read yaml file with Amazon credentials
import yaml
with open('credentials.yaml') as file:
    try:
        ama_auth = yaml.safe_load(file)
        aws_credentials = dict(
          refresh_token =  ama_auth['default']['refresh_token'], 
          lwa_app_id =  ama_auth['default']['lwa_app_id'], 
          lwa_client_secret =  ama_auth['default']['lwa_client_secret'],
          aws_secret_key =  ama_auth['default']['aws_secret_key'],
	  aws_access_key =  ama_auth['default']['aws_access_key'],
          role_arn = ama_auth['default']['role_arn'])
    except yaml.YAMLError as exc:
        print(exc)
#
from sp_api.base import Marketplaces
from sp_api.api import listings_items, product_type_definitions
print('pass import: ')
#
seller_id = 'AXXXXXXXXXXXX'
marketplace_ids = ['ATVPDKIKX0DER']
#
# Provide Amazon Authentication
res_lists_auth = ListingsItems(credentials=aws_credentials, marketplace=Marketplaces.US)
print('pass auth: ')
#
# Call Get Listings items API
ama_listing_item = res_lists_auth.get_listings_item(seller_id,'1-029025',marketplaceIds=marketplace_ids)
print('Response Listing item: ',ama_listing_item)

//////////////////////////////////////////////////////////////////////////////////////

Complete Python output:
pass import: 
Traceback (most recent call last):
  File "E:/python-amazon-sp-api-master/ListingsItems_api.py", line 38, in <module>
    res_lists_auth = ListingsItems(credentials=aws_credentials, marketplace=Marketplaces.US)
NameError: name 'ListingsItems' is not defined

////////////////////////////////////////////////////////////////////////////////////////

 I also checked the listings_items.py API and the class name spelling is correct.

import urllib.parse

from sp_api.base import Client, sp_endpoint, fill_query_params, ApiResponse

class ListingsItems(Client):
    """
    ListingsItems SP-API Client
    :link: 

    The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.

For more information, see the [Listings Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md).
    """

    @sp_endpoint('/listings/2021-08-01/items/{}/{}', method='DELETE')
    def delete_listings_item(self, sellerId, sku, **kwargs) -> ApiResponse:
        """
        delete_listings_item(self, sellerId, sku, **kwargs) -> ApiResponse
        Delete a listings item for a selling partner.
        **Usage Plans:**
        ======================================  ==============
        Rate (requests per second)               Burst
        ======================================  ==============
        5                                       10
        ======================================  ==============
        The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
        Args:
            sellerId:string | * REQUIRED A selling partner identifier, such as a merchant account or vendor code.
            sku:string | * REQUIRED A selling partner provided identifier for an Amazon listing.
            key marketplaceIds:array | * REQUIRED A comma-delimited list of Amazon marketplace identifiers for the request.
            key issueLocale:string |  A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.
        Returns:
            ApiResponse:
        """

        return self._request(fill_query_params(kwargs.pop('path'), sellerId, sku), data=kwargs)

    @sp_endpoint('/listings/2021-08-01/items/{}/{}', method='GET')
    def get_listings_item(self, sellerId, sku, **kwargs) -> ApiResponse:

////////////////////////////////////////////////////////////////////////////////////////////////////////////

**To Reproduce**
 1: Create a credentials.yaml file with AWS Amazon credentials
 2. Create a Python program like the My Python code above.  Assign a valid seller_id.

**Expected behavior**
pass import:
pass auth: 
Response Listing item: {Api response}

**Desktop (please complete the following information):**

 - OS: Windows 

**Additional context**

**Comment by AVazquezf** [comment]
Sorry, my issue was close immediately. Is this a bug?  Or there is already a solution?

Arlene

**Comment by saleweaver** [comment]
Sorry, forgot to comment. You never import ListingsItems, simple programming error and unrelated to the library. 

from sp_api.base import Marketplaces
from sp_api.api import listings_items, product_type_definitions
print('pass import: ')


import ListingsItems instead.

**Comment by AVazquezf** [comment]
Ok. Thank you!
 
 It works with import ListingsItems!

from sp_api.api import ListingsItems
#
res_lists_auth = ListingsItems(credentials=aws_credentials, marketplace=Marketplaces.US)
