### ISSUE TITLE
亚马逊服务商API如何申请

### ISSUE THREAD

**Issue by Yvan8** [saleweaver/python-amazon-sp-api#1083]
1，亚马逊服务商API指的是什么？是否是sp-api？
2，如何申请
thanks

**Comment by olycats** [comment]
你在哪裡看到 亚马逊服务商API 的? 建議提供上下文

**Comment by guoshuaichao** [comment]
我的领导在网上看到的，他让我在研究一下，自己走一遍申请流程

**Comment by guoshuaichao** [comment]
我查了好久，并没有在网站上面看到任何关于亚马逊服务商API的信息，后面我问了chatgpt，他回复说，服务商API是sp-api的一部分，但是我并没有找到它的的申请方案，我还在亚马逊店铺后台开了CASE，亚马逊回复中也并没有说明什么是亚马逊服务商API，但是告诉我们可以通过付费的方式来提高我们的sp-api的请求速度，并且可以针对某个接口进行付费

**Comment by olycats** [comment]
你主管要你做的專案是什麼? 你們公司是做電商的嗎?

**Comment by guoshuaichao** [comment]
我们是做电商公司的，主要通过亚马逊平台来销售我们的产品，现在我们通过sp-api已经拿到了我们自己店铺的数据，但是后面部门要做大，要做ERP，现有的sp-api的请求速度达不到，需要更快得请求速度，

**Comment by guoshuaichao** [comment]
不知道有没有亚马逊服务商API这个名词

**Comment by saleweaver** [comment]
I'm sorry but I don't speak your language. Please let me know if there's something I can do
