### ISSUE TITLE
Catalog v0 depreccated since 30th September 2022

### ISSUE THREAD

**Issue by tilschuenemann** [saleweaver/python-amazon-sp-api#1094]
**Which API - Endpoint is your request about.**

Catalogue endpoint: Amazon SP Docs state the Catalog endpoint with version v0 was shut down on 30th September 2022.

Are there any plans on implementing the new v2 (or v1) to regain this functionality?

**Comment by saleweaver** [comment]
Yeah. Use CatalogItems
