### ISSUE TITLE
Assume Role

### ISSUE THREAD

**Issue by definedfunctions** [saleweaver/python-amazon-sp-api#11]
Is it possible to not require the Assume Role permission for the role arn if the role has sufficient permission already?  The role I'm using is the role that would "be assumed."

After a lot of troubleshooting with sp-api support, we found that the assume role permission was causing my API requests to fail.  After removing the permission, I'm now able to write successful requests.  That said, I would prefer to start working with this library.

Here's the error message I'm currently receiving:

ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::72750xxxxxxx:user/spxxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::72750xxxxxxx:user/spxxxx

Let me know if any of this doesn't make sense.

**Comment by saleweaver** [comment]
Hm. That's interesting, didn't have that before. From the error message, it totally sounds like you didn't have the permission to assume the role - Amazon's errors are misleading all the time though. What permission did the role have that you have removed?

**Comment by definedfunctions** [comment]
The user had two policies associated with it -- One intended to enable "Action": "sts:AssumeRole" and another for "Action": "execute-api:Invoke."

They had me remove both policies, then re-add "Action": "execute-api:Invoke."

From there I started making requests without using Assume Role and things started working properly.

**Comment by definedfunctions** [comment]
For example, I can retrieve results from /sales/v1/orderMetrics via python requests module but when using this library I received the AssumeRole error from my first comment.

In both instances I'm using the same credentials.

**Comment by saleweaver** [comment]
Ok, there's a part missing in Amazon's documentation about those policies, I could make it work only with the assume role call. I'll try to recreate this tomorrow and update you.

**Comment by definedfunctions** [comment]
Awesome, thanks.

**Comment by saleweaver** [comment]
The client needs a session token to sign the request, the session token is created by the assume role operation. So I don't think there's (and haven't found) a solution to this.

**Comment by definedfunctions** [comment]
Okay. For what it's worth, I don't use the assume role operation and am able to create requests.

To get the access token required for making requests, I use my refresh_token, client_id & client_secret in a post request to https://api.amazon.com/auth/o2/token.  The grant_type parameter is set to refresh_token.  The client_id and client_secret are the id and secret associated with the iam user.  

That request returns an access_token along with the original refresh_token.  The access_token is used in the requests as the x-amz-access-token.

In order to get the refresh_token that's used to retrieve the access_token for requests, you send a post request to the same endpoint(/auth/o2/token).  Only this time the request includes the following parameters:

grant_type = authorization_code 
code= spapi_oauth_code
redirect_uri = found in the app details
client_id = LWA id
client_secret = LWA secret

\\

Maybe you already know all of this, but if nothing else the overview might end up being helpful for someone who stumbles on it by accident.
