### ISSUE TITLE
Missing x-amzn-RateLimit-Limit information 

### ISSUE THREAD

**Issue by segalb** [saleweaver/python-amazon-sp-api#111]
The exceed quota exception is not throwing information about the request. 
it is missing : x-amzn-RateLimit-Limit

Based on the following [documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md), the information will allow better api request and usage of the rate limit.

**Comment by saleweaver** [comment]
Please Open this issue in Amazon's repository instead.
