### ISSUE TITLE
Non-expressive exception on decoding errors

### ISSUE THREAD

**Issue by tmechsner** [saleweaver/python-amazon-sp-api#1143]
**Describe the bug**
When calling `Reports.get_report_document()` with an encoding (specified by the `character_code` argument) that cannot decode all characters in the report document, a very unexpressive `TypeError` is thrown in the code where it tries to write bytes to a file opened in text mode.

**To Reproduce**

Difficult to reproduce - try to find an encoding that cannot decode the bytes of a report you're trying to download.

**Expected behavior**

In earlier versions of this library, a `UnicodeDecodeError` was thrown in these situations. This exception has a speaking name and it popped up at the position in the code where the api response body is decoded. So it is directly understandable what happened. 

**Desktop (please complete the following information):**

 - OS: Mac, debian (bookworm)

**Additional context**

This error is rooted in this commit:
https://github.com/saleweaver/python-amazon-sp-api/commit/5581b461319a51aa53db5496c6c4854d487df331
Before this commit the `UnicodeDecodeError` was thrown at this location in the code. Now any exception gets caught and dismissed and instead of handling the error the document is passed on as bytes object where it usually gets passed on as a string. This causes problems when providing the `Reports.get_report_document()` method with a file opened in text mode (which works fine until a report appears that requires a different encoding). I don't know what that "bug from 0.18.5" is that is referred to in the commit description. If someone could provide further information (maybe the author of the commit - @olycats ?) I'd be willing to provide a PR.

**Comment by olycats** [comment]
Hey @tmechsner I don't really have an idea what's going on, but if there is an issue with that commit, I am okay to revert it.
The commit was to fix the issues caused by a bug from the Amazon API back in June.
For more context please see: https://github.com/saleweaver/python-amazon-sp-api/issues/1085
