### ISSUE TITLE
FulfillmentInbound BUG

### ISSUE THREAD

**Issue by TSLdob** [saleweaver/python-amazon-sp-api#1149]
When I was trying to download shipment information using the method below, I found that most endpoints of FulfillmentInbound do not recognize parameters other than MarketplaceId, QueryType, and ShipmentStatusList.

For example, parameters like LastUpdatedAfter, LastUpdatedBefore, and NextToken are ignored.

So, even when I correctly passed the next_token_param while using the load_all_pages decorator, I couldn't paginate using the token. It would always return data from the first page and enter an infinite loop.

I'm not sure if it's a bug in my code or an issue with this specific Amazon endpoint because my code works correctly with data from other endpoints.

def download_fba():
    server = FulfillmentInbound(credentials=credentials, marketplace=marketplace)

    @throttle_retry()
    @load_all_pages(next_token_param='nextToken')
    def fba(**kwargs):
        return server.get_shipments(**kwargs)

    for page in fba(MarketplaceId='A1VC38T7YXB528', QueryType='SHIPMENT', ShipmentStatusList='CLOSED'):
        print(page)

**Comment by threemonks** [comment]
@TSLdob Is this issue resolved? Would you mind sharing how you resolved it? I am facing the same issue with not just FulfillmentInbound, but also Finances.list_financial_events, CatalogItems.search_catalog_items and Reports.get_reports, whenever I decorate the method with load_all_pages, the query to retrieve following result pages using next_token_param seems to be ignored, and I keep getting the first result page repeatedly, essentially an infinite loop.

Thanks

**Comment by TSLdob** [comment]
@threemonks When requesting the next page of data, do not pass in the shipment_id but directly use NextToken

**Comment by threemonks** [comment]
> @threemonks When requesting the next page of data, do not pass in the shipment_id but directly use NextToken

Thanks for sharing the solution.

**Comment by TSLdob** [comment]
> > @threemonks When requesting the next page of data, do not pass in the shipment_id but directly use NextToken
> 
> Thanks for sharing the solution.
> 
> I tried to do that, but the API function call `FulfillmentInbound().shipment_items_by_shipment` requires a positional parameter shipment_id, right? How do you omit that? Passing None? Or you are calling the other API function `FulfillmentInbound().shipment_items` instead? I noticed these two API calls have different end point, "/fba/inbound/v0/shipments/{}/items" for `shipment_items_by_shipment()` and "/fba/inbound/v0/shipmentItems" for `shipment_items`. If I call `shipment_items` with query parameter NextToken only, it seems to always give this error: "Either the ShipmentId or a pair of LastUpdatedAfter and LastUpdatedBefore must be passed in input", I also even tried to provide ShipmentId to API function call `shipment_items`, but still get the same error.

Send the shipment_id during the first request, obtain the token, and then use the token directly

Here is the sample code
```python

        res = xxx.shipment_items_by_shipment(shipment_id=shipment_id,
                                                MarketplaceId=MarketplaceIdXXX
        next_token = res.payload.get('NextToken', None)

        if next_token:
            @throttle_retry()
            @load_all_pages()
            def _fba_shipments_item(**_kwargs):
                return xxx.shipment_items(**_kwargs)

            for page in _fba_shipments_item(QueryType='NEXT_TOKEN',
                                            MarketplaceId=MarketplaceIdXXX,
                                            NextToken=next_token):
                
```
