### ISSUE TITLE
How to get Inventory data of fulfillment by merchant

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#116]
I want to access the inventory data of my seller account and by accessing the Inventories end point it is only giving inventory data of  fulfillment by amazon data not fulfillment by merchant.
can you please tell me how to get inventory data of fulfillment by merchant?
Thank you

**Comment by kevincojean** [comment]
> I want to access the inventory data of my seller account and by accessing the Inventories end point it is only giving inventory data of  fulfillment by amazon data not fulfillment by merchant.
> 
> can you please tell me how to get inventory data of fulfillment by merchant?
> 
> Thank you
> 
> 

I believe you need to query for an inventory report using the report app endpoint, that's how I do it for my inventory.

**Comment by ritik-novostack** [comment]
@kevincojean  can u please provide tell me step by step that how can i procced? because its really helpful for me otherwise i may loose my job thank you
