### ISSUE TITLE
SP_API_ACCESS_KEY problem

### ISSUE THREAD

**Issue by 286844626** [saleweaver/python-amazon-sp-api#118]
I received this error, what is the reason：

![image](https://user-images.githubusercontent.com/34543121/114010900-30bb5880-9897-11eb-83ef-a99cf8045906.png)

**Comment by saleweaver** [comment]
Hi! Can you please explain what you are doing that causes the error?

**Comment by 286844626** [comment]
This is my code：
`# Import datetime and timedelta from python's datetime module
# https://docs.python.org/3/library/datetime.html
from datetime import datetime, timedelta

# Import the Orders class from python-amazon-sp-api
from sp_api.api import Orders
from sp_api.base import SellingApiException, Marketplaces

# Fill in credential info here
credentials = dict(
    refresh_token="",
    lwa_app_id=" ",
    lwa_client_secret=" ",
    aws_secret_key=' ',
    aws_access_key='hQd7B6m/7ccFxxxX96v5FaRAN6XXRhzfwX05Q',
    role_arn=' ',
)

try:
    # Get orders created after 1 day ago
    res = Orders(credentials=credentials, marketplace=Marketplaces.GB).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=1)).isoformat())
    print(res)

# If something goes wrong, print out the exception
except SellingApiException as ex:
    print(ex)`
