### ISSUE TITLE
Docs website offline

### ISSUE THREAD

**Issue by tgehrs** [saleweaver/python-amazon-sp-api#1185]
**Describe the bug**
When I navigate to the documentation for this project, the site cannot be reached. 

**To Reproduce**

Navigate to https://sp-api-docs.saleweaver.com/ on any browser

**Expected behavior**

Should open the documentation.

**Desktop (please complete the following information):**

Chrome and Safari iOS

**Additional context**

 Not sure if this is an issue with the saleweaver.com domain or the docs themselves. Readthedocs [build page](https://readthedocs.org/projects/python-amazon-sp-api/builds/22032424/) for this project shows an error message with the build of the documentation because `.readthedocs.yaml` is missing. I will add this file in a PR, just in case this is the issue

<img width="878" alt="Screen Shot 2023-09-26 at 9 57 22 AM" src="https://github.com/saleweaver/python-amazon-sp-api/assets/9788919/55165421-0b1e-4d93-bc2e-4eae4f7f5a51">

**Comment by saleweaver** [comment]
I merged the PR, I'm currently away, docs go back online next week. Sorry for the inconvenience

**Comment by michaelc197-sh** [comment]
@saleweaver any update on docs availability?
