### ISSUE TITLE
AWS credentials still required as a place holder

### ISSUE THREAD

**Issue by immortal-beast** [saleweaver/python-amazon-sp-api#1213]
**Describe the bug**

After the latest update, the readme says that aws_access_key and aws_secret_key are not required anymore but can still be passed and they will be silently ignored. However this is not true, they are required as a placeholder atleast. 

If they are not present we get this error:
KeyError: 'AWS Access Key ID and Secret Access Key are required' in 'class AWSSigV4' (aws_sig_v4.py)

**To Reproduce**

Just set the config without aws_access_key and aws_secret_key fields in it. Then try any api call.

**Comment by saleweaver** [comment]
The file doesn't even exist anymore, please update to the latest version and try again
