### ISSUE TITLE
Replenishment API

### ISSUE THREAD

**Issue by discover59** [saleweaver/python-amazon-sp-api#1233]
Is Replenishment API available in this library?

https://developer-docs.amazon.com/sp-api/docs/replenishment-api-v2022-11-07-reference#overview

**Comment by saleweaver** [comment]
It isn't yet. Want to open a PR?

**Comment by discover59** [comment]
Looks like someone was monitoring new issues here and already created PR. 😆 
https://github.com/saleweaver/python-amazon-sp-api/pull/1234

**Comment by saleweaver** [comment]
It's available now :)
