### ISSUE TITLE
Boto3 library

### ISSUE THREAD

**Issue by gg1198** [saleweaver/python-amazon-sp-api#1237]
Is it required to install boto3 after getting rid of AWS Signature Version 4 authentication?

**Comment by adamantike** [comment]
This would be a good improvement, by making `boto3` parts of an extras. For that to happen, imports for `boto3` and `botocore` handle `ImportError`, and `FromSecretsCredentialProvider` should be a no-op when these libraries aren't installed.

This is similar to how `FromCachedSecretsCredentialProvider` works, by depending on the optional dependency `aws-secretsmanager-caching`.

**Comment by saleweaver** [comment]
Yes, will make this work

**Comment by saleweaver** [comment]
From version 1.3.0, boto3 is an optional dependency
