### ISSUE TITLE
90011 - The file's column headings are missing or invalid - FeedApi

### ISSUE THREAD

**Issue by shintaii** [saleweaver/python-amazon-sp-api#127]
**Describe the bug**
When calling the Feeds.submit_feed() it results eventually in an error at Amazon Sellercentral. 
```
Feed Processing Summary:
	Number of records processed		0
	Number of records successful		0

original-record-number	sku	error-code	error-type	error-message
0		90011	Fatal	The file's column headings are missing or invalid. To correct this error, download the template again and use that new copy, or insert the correct column headings as row two of your existing file.
```

**To Reproduce**

Run this file.
[main.zip](https://github.com/saleweaver/python-amazon-sp-api/files/6312692/main.zip)

**Expected behavior**

A "Correct" processed file on Amazon Seller Central. No Technical Errors.

**Desktop (please complete the following information):**

 - OS: [Windows]

**Additional context**
Using Python 3.8
On windows in a clean virtual ENV with just sp-api installed, nothing more.

**Comment by saleweaver** [comment]
Please add the file's content to the issue. Thank you.

**Comment by shintaii** [comment]
> Please add the file's content to the issue. Thank you.

The content is just one line. It is in the script:
[feed_row_template.format('889698516204','889698516204',4,11,0,"a","4","N","Y")]

But here it is:
[test.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6313163/test.txt)

**Comment by shintaii** [comment]
Closed? Why?

**Comment by saleweaver** [comment]
Hi,

I can’t help you without your code. Since everything works for me, all I can say is that I can’t reproduce your problem. I’ve asked you to post code, you’ve posted a single line which is only a syntax error. Please post an answer- and reproducible problem report, then I’m happy to assist.
Am 14. Apr. 2021, 21:30 +0200 schrieb Patrick Gerrits ***@***.***>:


Closed? Why?
