### ISSUE TITLE
Problem with request

### ISSUE THREAD

**Issue by sw69** [saleweaver/python-amazon-sp-api#129]
Hi,
we have communication problem with amazon.
Our client logs in to our service where he clicks button "Log in Amazon". He is then redirected to url https://sellercentral.amazon.pl/apps/authorize/consent?application_id=amzn1.sellerapps.app.xxxx-xxxx-xxx-xxx-xxx&state=here_is_unique_uid. On this page our partner accepts the usage for our application and is redirected back, from that action we get selling_partner_id and spapi_oauth_code. After that we send request on https://api.amazon.com/auth/o2/token  with data:
{'grant_type': "authorization_code",
                    'code': spapi_oauth_code,
                    'redirect_uri': redirect_url,
                    'client_id': AMAZON_CLIENT_ID,     
                    'client_secret': AMAZON_SECRET
                    }
where AMAZON_CLIENT_ID and AMAZON_SECRET are LWA credentials of app. In response we receive access_token and refresh token. Till this point everything works fine.

Now we try to get orders data:
1.
We request Login with Amazon access token on /auth/o2/token with params: client_id, client_secret (LWA credentials of app) grant_type=refresh_token, refresh_token=refresh token we have from previous step. In response we receive new access_token and refresh_token.

2.
We create assume role request on sts.amazonaws.com  using AWS_ACCESS from AWS for credential and AWS_SECRET from AWS for computing signature. From that response we get SessionToken and accesskeyid.

3.
Final request for orders: GET on sellingpartnerapi-eu.amazon.com/orders/v0/orders in Authorization header for credential we use accesskeyid from assume role request, for X-Amz-Access-Token header we use access token from 1st request, and for X-Amz-Security-Token we send sessiontoken received from assumrole request for that data we receive 403 forbidden error
HTTP/2.0 403 Forbidden
Content-Length: 141
Content-Type: application/json
Date: Wed, 07 Apr 2021 13:33:57 GMT
X-Amz-Apigw-Id: daku6GYXDoEFQPw=
X-Amzn-Errortype: AccessDeniedException
X-Amzn-Requestid: 55ff0680-a7c1-412d-830d-cc3b018ea1b9

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

We don't have idea what is wrong. Our app have a access  permission to get order.

**Comment by mrmosconi** [comment]
Same

**Comment by meetvaghasiya** [comment]
same here any solution for it?

**Comment by saleweaver** [comment]
I'd your application published?

**Comment by meetvaghasiya** [comment]
not yet

**Comment by saleweaver** [comment]
add version=beta to the params and try again

**Comment by mk-hasan** [comment]
same problem with me...

**Comment by saleweaver** [comment]
> Hello,
> 
> I'm facing the same problem with self authorization. My app isn't published either, status is draft.
> 
> > add version=beta to the params and try again
> 
> I guess we can't add this parameter into the code. Is there any other solution?
> 
> EDIT: According to the document self authorization doesn't require the app to be published, therefore the cause of my problem must be different:
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization

Yes, your problem doesn't seem to be remotely related to the thread. Please just follow the documentation on how to self authorize, nothing from this thread applies to your use case.

**Comment by saleweaver** [comment]
@sw69 Did you find a solution to this?

**Comment by saleweaver** [comment]
@mrmosconi @sw69 @mk-hasan @NephewOfGod Can someone please have a look if the refresh token returned from last commit (https://github.com/saleweaver/python-amazon-sp-api/commit/5d32a0aae123365b656b1375eb2f39f85466ac85) works in subsequent requests:

```
from sp_api.auth import AccessTokenClient

auth = AccessTokenClient().authorize_auth_code(<auth_code>)

```

**Comment by saleweaver** [comment]
Please use 

```
from sp_api.base import AccessTokenClient

auth = AccessTokenClient().authorize_auth_code(<auth_code>)

```

to get the refresh token, then pass the obtained refresh_token to one of the clients

```
from sp_api.api import Sales
res = Sales(refresh_token='At...').<whatever>()
```

**Comment by bitliner** [comment]
This does not work.

In particular, the code above fails with a similar error:

```
auth = AccessTokenClient(
           ^^^^^^^^^^^^^^^^^^
  File "/login-with-amazon-wUWU3fmb-py3.12/lib/python3.12/site-packages/sp_api/auth/access_token_client.py", line 25, in __init__
    self.cred = Credentials(refresh_token, credentials)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/login-with-amazon-wUWU3fmb-py3.12/lib/python3.12/site-packages/sp_api/auth/credentials.py", line 6, in __init__
    self.client_id = credentials.lwa_app_id
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lwa_app_id'
``` 

while it is not clear how to pass credentials.

In addition, it is not clear how to use this library with the web app authorization flow, that is the only usable flow when an app is published publicly and there is no way to get the refresh token.

Does this library supports sp-api when the app is public?
