### ISSUE TITLE
Missing or invalid request parameters: [marketplaceIds] 

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#13]
**Describe the bug**
I am trying to get order metrics from the Sales model
 and I am getting an error 
`[{'message': 'Missing or invalid request parameters: [marketplaceIds]', 'code': 'InvalidInput'}]
`

**To Reproduce**
```
    from sp_api.api import Sales
    from sp_api.base import Granularity

    sales = Sales()
    sales.get_order_metrics(interval=((datetime.utcnow() - timedelta(days=7)).isoformat(), datetime.utcnow().isoformat()),
                             granularity=Granularity.DAY)
```

**Comment by saleweaver** [comment]
Thanks for reporting! This is fixed in the last commit.

**Comment by mohamedfawzy96** [comment]
Glad to help

**Comment by mohamedfawzy96** [comment]
Would be great also if u can make them in release versions :) Thank you for developing this btw, its really helpful.

**Comment by saleweaver** [comment]
I wanted to start doing release versions once most of the api calls are implemented, we'll be there soon.
