### ISSUE TITLE
Add shipping api

### ISSUE THREAD

**Issue by ximo1984** [saleweaver/python-amazon-sp-api#134]
Hi,

First thanks for this project.

Could you add shipping api or explain how to add it to the project?
This is the reference: https://github.com/amzn/selling-partner-api-docs/tree/main/references/shipping-api

**Comment by jaredkipe** [comment]
I started this today, can get_command, will validate and improve shortly. https://github.com/saleweaver/python-amazon-sp-api/pull/135

**Comment by saleweaver** [comment]
Merged #135
