### ISSUE TITLE
Running Feeds.create_feed_document() in SANDBOX mode doesn't work

### ISSUE THREAD

**Issue by hobbsd** [saleweaver/python-amazon-sp-api#1352]
In `SANDBOX` mode (setting environment variable `AWS_ENV=SANDBOX`) I tried running `create_feed_document()` which sent a request with this body to the sandbox endpoint (I had set the `content_type` variable):
`{"contentType": "text/tab-separated-values; charset=utf-8", "path": "/feeds/2021-06-30/documents", "marketplaceIds": ["ATVPDKIKX0DER"], "MarketplaceIds": ["ATVPDKIKX0DER"]}`

The response was an "invalid input" error. I tried running the same request in Postman first with the production path, which worked, then with the sandbox path, which failed with the same "invalid input" error.

After a few more Postman tests, I found that the sandbox for `createFeedDocument` **only** succeeds with `{"contentType": "text/tab-separated-values; charset=UTF-8"}` as the complete body (and it's space- and case-sensitive).

That's the only function I tried so far, but I suspect that the other functions in sandbox mode might have similar issues.

**Comment by hobbsd** [comment]
I just noticed a closed issue regarding the sandbox that would've saved me some time (my bad). I guess the documentation should have mention of the sandbox removed, or amend it to say that it doesn't work.

**Comment by saleweaver** [comment]
The sandbox only allows a fixed set of request bodies, as outlined in the endpoint's scheme. It's a complete waste of time using it.
