### ISSUE TITLE
load_all_pages not working with AplusContents list_content_document_asin_relations

### ISSUE THREAD

**Issue by tilschuenemann** [saleweaver/python-amazon-sp-api#1389]
**Describe the bug**
While using the `AplusContent ` API I stumbled upon the following issue:

Calling `list_content_document_asin_relations()` on a A+ content document with more then 1000 ASINs will only return the first 1000 ASINs, if includedDataSet is empty. This is problematic when you want to fetch metadata for all ASINs for a A+ document.

**To Reproduce**

```python

from sp_api.api import AplusContent
from sp_api.util import load_all_pages
from sp_api.base import Marketplaces

crk = "" # this A+ has 1066 ASINs
mp_id = "A1PA6795UKMFR9"
mp = Marketplaces.DE
credentials = {
    "lwa_app_id": "",
    "lwa_client_secret": "",
    "refresh_token": "",
}


ac = AplusContent(
    credentials=credentials,
    marketplace=mp,
)
 res_1 = ac.list_content_document_asin_relations(contentReferenceKey=crk, marketplaceId=mp_id, includedDataSet="METADATA")
print(len(res_1.payload["asinMetadataSet"]))  # 1000


res_2 = ac.list_content_document_asin_relations(contentReferenceKey=crk, marketplaceId=mp_id, includedDataSet="")
print(len(res_2.payload["asinMetadataSet"]))  # 1066, but no metadata :(

# In order to use load_all_pages, I'd check for the name of key containing the next token:
print(res_1.next_token) # None
print(res_1.payload["nextPageToken"])  # 'B0C8CK2D22'

# What I would expect to work, having read the docs:
# @load_all_pages(next_token_param="nextPageToken")
# def list_content_document_asin_relations(*args, **kwargs):
#     return ac.list_content_document_asin_relations(*args, **kwargs)
```

Upon further inspection of  `load_all_pages()`, [one can see that only res.next_token gets checked](https://github.com/saleweaver/python-amazon-sp-api/blob/a959132e01009ce7f087e4ddc22ec04e2563c867/sp_api/util/load_all_pages.py#L33).

My workaround:
```python
@load_all_pages(next_token_param="pageToken")
def list_content_document_asin_relations(*args, **kwargs):
    tmp = ac.list_content_document_asin_relations(*args, **kwargs)
    tmp.next_token = tmp.payload["nextPageToken"]
    return tmp
res_3 = []
for page in list_content_document_asin_relations(contentReferenceKey=crk, marketplaceId=mp_id, includedDataSet="METADATA"):
    res_3 += page.payload["asinMetadataSet"]
print(len(res_3))  # 1066, with metadata :)
```

**Expected behavior**

When specifying `next_token_param` in `load_all_pages()`, it should check the payload as well.

**Desktop (please complete the following information):**

 - OS: WSL2 on Windows 11.

**Comment by saleweaver** [comment]
Hi, 

thanks for raising this. Please upgrade to 1.5.1, should be fixed there.

**Comment by saleweaver** [comment]
.... @tilschuenemann you can use the load_all_pages decorator like described in the docs, the next token param gets parsed for the endpoint now...
