### ISSUE TITLE
Environment variables as params

### ISSUE THREAD

**Issue by alesconti** [saleweaver/python-amazon-sp-api#14]
In our company we have 2 different accounts, one for European market and one for US. 
Do you think is possible to pass environment variables as params to the library ?

**Comment by saleweaver** [comment]
I was thinking about that already, I thought having an option to configure the credentials as params would make sense, yes. I'll be working on this when I got time the next couple of days.

**Comment by alesconti** [comment]
Thanks a lot

**Comment by saleweaver** [comment]
This is now implemented in the latest release

#15

**Comment by saleweaver** [comment]
@alesconti Does the change work for your use case?

**Comment by alesconti** [comment]
I think it's perfect ! Thanks a lot
