### ISSUE TITLE
GET /catalog/2022-04-01/items

### ISSUE THREAD

**Issue by Forceres** [saleweaver/python-amazon-sp-api#1453]
**Describe the bug**
GET /catalog/2022-04-01/items doesn't coincide with Amazon sp-api docs, cannot pass sellerId, keywords are required (but in docs they are optional), not all includeData options are supported. To put it in a nutshell, I need to get products from specific seller by seller id
**To Reproduce**

Launch this code:

```python
self.catalog_items_api = CatalogItems(marketplace, **credentials)

products = self.catalog_items_api.search_catalog_items(sellerId=SELLER_ID,
                                                                       includedData="relationships,attributes,dimensions,identifiers,images,productTypes,salesRanks,summaries",
                                                                       marketplaceIds=["ATVPDKIKX0DER"])

```

**Expected behavior**

To get products from specific seller by seller id with pagination

**Desktop (please complete the following information):**

- ArchLinux

**Comment by saleweaver** [comment]
Hi, it should work by setting the correct version - does it?
