### ISSUE TITLE
AWD endpoints

### ISSUE THREAD

**Issue by BroncoMark** [saleweaver/python-amazon-sp-api#1464]
**Which API - Endpoint is your request about.**

Amazon's new Amazon Warehousing and Distribution API

**Additional context**

They have quietly released endpoints for Amazon Warehousing and Distribution API found here in their documentation:
https://developer-docs.amazon.com/sp-api/docs/awd_2024-05-09-reference

I would love this package to support these endpoints. I have attached a .py file that is a rough version of what I have been using to connect to these endpoints through this package, and hope it can serve as a good starting point for this feature.

[awd_api.zip](https://github.com/user-attachments/files/16182181/awd_api.zip)

**Comment by saleweaver** [comment]
Hi, thanks for raising this! Can you kindly create a PR with your changes?
