### ISSUE TITLE
The API for Catalog Items endpoint raise error if the includedData option is included with dimensions and relationships

### ISSUE THREAD

**Issue by siddhartha2202** [saleweaver/python-amazon-sp-api#1480]
**Describe the bug**
When the includedData attribute use the value "attributes or dimensions" of the CatalogItems.search_catalog_items(), raise an error

**To Reproduce**

 
res = CatalogItems().search_catalog_items(keywords=items_str, marketplaceIds='XXXXXXXX', includedData="summaries, dimensions")

**Expected behavior**

Return a the information

**Desktop (please complete the following information):**

Mac

**Additional context**

If the API is run from Postman with the same parameters there is no error, this only occurs if we use the library.

**Comment by saleweaver** [comment]
You have to set the version for catalogItems

**Comment by siddhartha2202** [comment]
Sorry, you're right, the problem was that I didn't read the documentation properly. I thank you infinitely for your support. The library works perfectly !!!!!!!
