### ISSUE TITLE
get_product_fees_estimate_for_sku white space issue

### ISSUE THREAD

**Issue by vgmasterx** [saleweaver/python-amazon-sp-api#1497]
When a SKU (Test 123) has a white space the following error will be returned: 'No ASIN found for SKU: Test+123. Please make sure the SKU is valid.'

I've tried encoding the SKU before the request, and tried leaving the SKU as is, but I cannot get the correct output.

**Comment by saleweaver** [comment]
Yeah, had a lot of trouble with this. Just use skus without a whitespace, Amazon doesn't like them.

**Comment by saleweaver** [comment]
Just out of interest, there are similar problems with the product pricing endpoint - have a look if one of the solutions there work for you

**Comment by vgmasterx** [comment]
Thanks for the reply. I am submitting the same SKU in the product pricing endpoint and it works as intended without any encoding. I tried the fee estimate request within postman without encoding the SKU and it seems to work.
