### ISSUE TITLE
AWD Version Class

### ISSUE THREAD

**Issue by BroncoMark** [saleweaver/python-amazon-sp-api#1504]
**Describe the bug**
The class that represents the AWD version number only inherits from the Enum class, and not also the str class. This leads to failing code any time any of the methods in the AWD file are called, because it cannot put the version in the url path.

It will specifically fail on line 176 in the client.py file, but can be resolved by adding str in the AmazonWarehousingAndDistributionVersion class, or line 7 of the amazon_warehousing_and_distribu.py file

**To Reproduce**

Call any of the AWD endpoints.

**Comment by saleweaver** [comment]
Thanks for reporting, fixed now
