### ISSUE TITLE
FulfillmentInbound API: list_packing_group_items returns all items for each packing group instead of segregating hazardous/non-hazardous items

### ISSUE THREAD

**Issue by i14g** [saleweaver/python-amazon-sp-api#1597]
Bug Description:
The FulfillmentInbound API's list_packing_group_items method is incorrectly returning all items in every packing group, regardless of hazard classification. This makes it impossible to determine which items should actually be packed together.
Steps to Reproduce:

Create an inbound shipment with two items and generate the packing options:

One hazardous item
One non-hazardous item

Call list_packing_group_items
Observe that both items appear in both packing groups

Current Behavior:

The API creates two separate packing groups
Each packing group lists ALL items, both hazardous and non-hazardous
There's no way to determine which items belong to which group

Expected Behavior:

Hazardous items should only appear in their designated packing group
Non-hazardous items should only appear in their designated packing group
Each item should appear in exactly one packing group
This would allow clear identification of which items can be safely packed together

**Comment by saleweaver** [comment]
Hi - I'm not sure if I can do something on the wrapper level, this sounds like an Amazon problem. Are there any options you can set?

**Comment by i14g** [comment]
I think you're right that it might be on the Amazon side of things, because I was looking at the wrapper and didn't see any issues. Plus I'm getting a response just not the right one. I'll reach out to developer support. Thanks!
