### ISSUE TITLE
boto3 client

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#16]
is it possible to initialise the boto3 client inside of the Client class constructor ? because every time I import any I need to intialise the the env variables even though I still didn't initialise the model . the file is the client.py
![Screen Shot 2021-01-28 at 15 16 41](https://user-images.githubusercontent.com/16167016/106150670-d8bbf380-617b-11eb-94d6-953f370afa66.png)

**Comment by saleweaver** [comment]
That has already changed in #15

**Comment by mohamedfawzy96** [comment]
Okay perfect thank you
