### ISSUE TITLE
Missing Amazon Vendor Shipping Endpoints

### ISSUE THREAD

**Issue by PGC-CBeyor** [saleweaver/python-amazon-sp-api#1608]
I was looking to use the VendorShipments endpoints to help replace our existing EDI connection with Amazon Vendor but found some of the required endpoints are missing.

**Which API - Endpoint is your request about.**
VendorShipments

**Missing Endpoints:**
SubmitShipments
GetShipmentDetails
getTransaction

**Comment by saleweaver** [comment]
Hi, thanks for the reminder 😀

I've added the methods to the VendorShipments client. The transactions seem to be part of a different client, sp_api.api.VendorTransactions
