### ISSUE TITLE
Marketplaces IE

### ISSUE THREAD

**Issue by seanyang715** [saleweaver/python-amazon-sp-api#1620]
The Amazon marketplace currently supports the Ireland market. Its Marketplace ID is A28R8C7NBKEWEA.

**Comment by saleweaver** [comment]
487b25c

**Comment by saleweaver** [comment]
5a59a71ec111a81bba2c9e985a434912252e4b06

**Comment by saleweaver** [comment]
Thanks - added the marketplace
