### ISSUE TITLE
Load all pages for reports not working

### ISSUE THREAD

**Issue by anova-git** [saleweaver/python-amazon-sp-api#1626]
Running a copy of the "load of all orders", modified to get all reports, only works if the number of reports retrieved is less than or equal to the page size; i.e., the pagination is not needed. It works fine for "load all orders" but not for reports. 

Code used:
```
@throttle_retry()
@load_all_pages(next_token_param='next_token')
def get_all_reports(client, **kwargs):
    return(client.get_reports(**kwargs))
```
```
try:
  client_reports = ReportsV2(credentials=CREDENTIALS)
  all_reports = []

  for page in get_all_reports(client_reports, 
                              reportTypes=['GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL'],
                              processingStatuses=["DONE"],
                              pageSize=100,
                              createdSince='2024-12-10'
                            ):

      for report in page.payload.get('reports'):
          all_reports.append(report)

  print(f'Total reports: {len(all_reports)}')
  print(all_reports)

except Exception as e:
  print('Exception while processing all reports:', e)
```

**To Reproduce**

It works fine when the next_token is null on the first call (using page size=100).
```
Total reports: 11
[{'reportType': 'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL', 'processingEndTime': '2024-12-20T06:31:37+00:00', 'processingStatus': 'DONE', 'marketplaceIds': ['ATVPDKIKX0DER'], 'reportDocumentId': ...
```
When changing pageSize=10, at least one next_token needed to be used. It loops forever until the quota is exceeded. Putting some traces on a copy of the original load_all_pages, it looks like a new token is returned in all calls (expected for the first one only for 11 reports and page size 10).

`Exception while processing all reports: [{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}]`

**Expected behavior**

Loop over the next_token without looping forever

**Desktop (please complete the following information):**

 - OS: Windows 10
 - python-amazon-sp-api-1.9.5
 - Python 3.12.6

**Comment by saleweaver** [comment]
Hi, I assume it's working when using the correct param

    @load_all_pages(next_token_param='nextToken')

**Comment by anova-git** [comment]
It does not work for me. On the response for the report, the name shown is "next_token".

` "next_token": "gTY0iaw+dWiudbTFBpV .....'`

Using the default next_token_param="NextToken" or passing the parameter explicitly:

```
@throttle_retry()
@load_all_pages()
def get_all_reports(client, **kwargs):
    return(client.get_reports(**kwargs))
```

`Exception while processing all reports: [{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}]`



```
@throttle_retry()
@load_all_pages(next_token_param="NextToken",)
def get_all_reports(client, **kwargs):
    return(client.get_reports(**kwargs))
```

`Exception while processing all reports: [{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}]`

Marco R.

**Comment by saleweaver** [comment]
Ah I see, I thought the functionality is in. 

For the reports endpoint, all other params but the next token have to be removed.

I'm not at the computer, can you please log kwargs in load_all_pages and post the output (with tokens removed...)

**Comment by anova-git** [comment]
Sure, I have the code using two calls, the first one with all parameters and the second one using only nextToken, and it works. It does not work if the "@load_all_papges is present. 

I tried to simplify the code for reports and other endpoints I needed. I can run it successfully, reading all orders but not reports.

**Comment by anova-git** [comment]
Here is what I saved before logging the issue. I removed the logging code from the main code. I am going to put it back and rerun it. I also ran it without the next token parm and got the same infinite loop.

```
next_token: removed
next_token_parm: next_token
updated kwargs: {
    "reportTypes": [
        "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL"
    ],
    "processingStatuses": [
        "DONE"
    ],
    "pageSize": 10,
    "createdSince": datetime.date(2024,
    12,
    10),
    "next_token": "removed"
}
next_token: removed
10
next_token_parm: next_token
updated kwargs: {
    "reportTypes": [
        "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL"
    ],
    "processingStatuses": [
        "DONE"
    ],
    "pageSize": 10,
    "createdSince": datetime.date(2024,
    12,
    10),
    "next_token": "removed"}
next_token: removed
10
```

**Comment by saleweaver** [comment]
If you post the output I can post a fix now, otherwise it will take some time until I come back to look myself.

**Comment by saleweaver** [comment]
Please use 1.9.6, I just pushed it. 

Usage

    @load_all_pages(next_token_param='nextToken', next_token_only=True)

**Comment by anova-git** [comment]
```
@throttle_retry()
@load_all_pages(next_token_param='nextToken', next_token_only=True)
def get_all_reports(client, **kwargs):
    return(client.get_reports(**kwargs))
```

`Total reports: 11`

.. All reports here ...

And it worked like a charm!

Thank you!

My mistake was fixed :)

Marco R.

**Comment by saleweaver** [comment]
Nice, also learned not to push code from mobile. Great day. 😂
