### ISSUE TITLE
Add support for multiple marketplaces by array

### ISSUE THREAD

**Issue by ciocca-dev** [saleweaver/python-amazon-sp-api#164]
Hi,
I cannot get orders from different Marketplaces all in once.
If I call  `get_orders(MarketplaceIds=["APJ6JRA9NG5V4"])` I correctly get the amazon IT orders.
Also if I call  `get_orders(MarketplaceIds=["A1PA6795UKMFR9"])` I correctly get the amazon DE orders.

But when I try pass the list of marketplaceIds it just returns the orders from the first marketplace.
For example if I call `get_orders(MarketplaceIds=["APJ6JRA9NG5V4", "A1PA6795UKMFR9"])` it returns only the IT orders.

In particular my code is this: `res = Orders(credentials=credentials, marketplace=Marketplaces.IT).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=time_step_in_days)).isoformat(), MarketplaceIds=["APJ6JRA9NG5V4", "A1PA6795UKMFR9"])
`

How can I solve?
Thanks in advice.

**Comment by saleweaver** [comment]
Can you please try to join the marketplaces and check if that returns all?

    MarketplaceIds= ','.join(["APJ6JRA9NG5V4", "A1PA6795UKMFR9"])

**Comment by ciocca-dev** [comment]
Yes, now it works! 
Thank you very much!

**Comment by saleweaver** [comment]
Add support for multiple marketplaces by array<Marketplace>
