### ISSUE TITLE
ListingsItems API delete_listings_item will not work as expected

### ISSUE THREAD

**Issue by denisneuf** [saleweaver/python-amazon-sp-api#169]
**Describe the bug**

The end_point apparently is wrong:
@sp_endpoint('/listings/2020-09-01/items/{}', method='DELETE')
as well the return
return self._request(fill_query_params(kwargs.pop('path'), sellerId), data=kwargs)

should be params and parse the sky, here is my proposal:

# Proposal
    @sp_endpoint('/listings/2020-09-01/items/{}/{}', method='DELETE')
    def delete_listings_item(self, sellerId, sku, **kwargs) -> ApiResponse:
        return self._request(fill_query_params(kwargs.pop('path'), sellerId, sku), params=kwargs)

# Includes sku and params to match:
'''
in the AMZ docs should be:

DELETE https://sellingpartnerapi-na.amazon.com/listings/2020-09-01/items/AXXXXXXXXXXXXX/ABC123
	?marketplaceIds=ATVPDKIKX0DER
	&issueLocale=en_US
'''

Type | Name | Description | Schema
-- | -- | -- | --
Path | sellerId  required | A selling partner identifier, such as a merchant account or vendor code. | string
Path | sku  required | A selling partner provided identifier for an Amazon listing. | string
Query | marketplaceIds  required | A comma-delimited list of Amazon marketplace identifiers for the request. | < string > array(csv)
Query | issueLocale  optional | A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.

**To Reproduce**

Regular Call will produce denied Resource Error

    # For reference only
    seller_sku = 'ABC123'
    seller_id = 'AXXXXXXXXXXXXX'
    issue_locale = 'es_ES'
    marketplace_id = 'ATVPDKIKX0DER'

    try:

        res = ListingsItems(account=store, marketplace=marketplace).delete_listings_item(
            sellerId=seller_id,
            sku=seller_sku,
            marketplaceIds=marketplace_id,
            issueLocale=issue_locale
        )

        logging.info(res)

    except SellingApiException as ex:
        print(ex)

**Expected behavior**

Make the regular call and obtain the Api Response payload

'payload': {'issues': [],
         'sku': 'ABC123',
         'status': 'ACCEPTED',
         'submissionId': 'c923c7e0976c443e89e86b41xxxxxxxx'}}

**Desktop (please complete the following information):**

 - OS: Mac 10.15.7 

**Additional context**

Apparently this problem will happen in the def patch_listings_item(self, sellerId, **kwargs) -> ApiResponse: but haven't check full yet

**Comment by saleweaver** [comment]
Thanks, the generator doesn't seem to work with 2 path variables. Can you create a pull request for the endpoint?

**Comment by denisneuf** [comment]
Ok @saleweaver the pull request is created, have a nice day!
