### ISSUE TITLE
CatalogItems API return an error

### ISSUE THREAD

**Issue by 854350999** [saleweaver/python-amazon-sp-api#178]
from sp_api.api import CatalogItems

res = CatalogItems(credentials=credentials).search_catalog_items(keywords=["usb cable"],marketplaceIds=["ATVPDKIKX0DER"])

This is a request I made. I think the ```parameters``` of the request are sufficient and correct, but it still reported a ```json format error```.

json.decoder.JSONDecodeError: Invalid control character at: line 4 column 197 (char 218)

**Comment by denisneuf** [comment]
keywords parameter is a string separated by commas:
keywords = "obd2,obd,diagnosis"
you are passing a string separated by space ["usb cable"] that will causes the error, just try this:

res = CatalogItems(credentials=credentials).search_catalog_items(keywords=["usb,cable"],marketplaceIds=["ATVPDKIKX0DER"])

will get a good response:

 'payload': {'items': [{'asin': 'B092QL72QJ',
                        'summaries': [{'brandName': 'Cable Matters',
                                       'itemName': 'Cable Matters USB C USB B '
                                                   'Cable',
                                       'manufacturer': 'Cable Matters',
                                       'marketplaceId': 'A1RKKUPIHCS9HS'}]},
...

<!DOCTYPE html>

Type | Name | Description | Schema | Default
-- | -- | -- | -- | --
Query | keywords  required | A comma-delimited list of words or item identifiers to search the Amazon catalog for. | < string > array(csv) | -


[https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md)

**Comment by saleweaver** [comment]
The problem is the url encoding, have this on my list.
