### ISSUE TITLE
Print issue

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#18]
For some reason this commit here didn't go in version 0.1.2 
https://github.com/saleweaver/python-amazon-sp-api/commit/c42ff0a60b9f78127c167a507dda04da9d1a5fa8#diff-fc7273734daad993dc59ccc3a0a8748fab5c950f560990bf70be387c6a8ccd2dL15

when I upgraded to 0.1.2 I got these print statements

**Comment by saleweaver** [comment]
Right, please use 0.1.3

**Comment by mohamedfawzy96** [comment]
okay thank you
