### ISSUE TITLE
Exception Inheritance Does Not Play Nicely With Flask

### ISSUE THREAD

**Issue by CouchMaster789** [saleweaver/python-amazon-sp-api#180]
**Describe the bug**
Exceptions defined by python-amazon-sp-api are inheriting from `BaseException` when they possibly should be inheriting from `Exception`. As far as I understand, `BaseException` is for special exceptions. This proves to be a real issue when using Flask. Error handlers can only be created for errors that inherit from `Exception` specifically.

**To Reproduce**

Create a flask app that uses this library with all relevant credentials included. Then perform an action that would raise an error (or just actively raise one of the errors) when using a route.

**Expected behavior**

I expected the flask error handler to nicely handle the errors by catching them, instead it throws its own error saying that the errors must inherit from `Exception`.

**Desktop (please complete the following information):**

 - OS: Windows

**Additional context**

> The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new exceptions from the Exception class or one of its subclasses, and not from BaseException. More information on defining exceptions is available in the Python Tutorial under User-defined Exceptions.
https://docs.python.org/3/library/exceptions.html

**Solution**
Simply update the exception classes to inherit from `Exception` instead of `BaseException`. That is, the exception definition found [here](https://github.com/saleweaver/python-amazon-sp-api/blob/389cca687a48da2387dac45d4352718dc60aaeec/sp_api/base/exceptions.py#L1) should replace `BaseException` with `Exception`.

**Comment by saleweaver** [comment]
Thanks for reporting this, this is fixed now.

**Comment by CouchMaster789** [comment]
Thanks for the super quick fix! Appreciate it.
