### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#19]
I was thinking of adding a variable in the env to say if its a sandbox or not, and then inside of the Marketplaces enum I will choose the urls depending if its sandbox or not. Would that be okay with you ?

**Comment by saleweaver** [comment]
This would be brilliant, yes. Can you create a pull request? This would make automated testing a lot easier...

**Comment by mohamedfawzy96** [comment]
https://github.com/saleweaver/python-amazon-sp-api/pull/20 
I created this pull request, but for testing u need to take care that sometimes some apis need special variables for example getting orders will something like that        sales.get_orders(CreatedAfter="TEST_CASE_200")

**Comment by mohamedfawzy96** [comment]
Also don't know if this kind of implementation is fine with you.

**Comment by saleweaver** [comment]
I'll check it in a few minutes. Thank you!

**Comment by saleweaver** [comment]
I've merged it in now. Thanks, that will help - I wanted to do some testing at next, that's perfect
