### ISSUE TITLE
TypeError: get_item_eligibility_preview() takes 1 positional argument but 4 were given

### ISSUE THREAD

**Issue by DavidRHid** [saleweaver/python-amazon-sp-api#192]
Type error when trying to run get_item_eligibility_preview(), I think there might be a problem on line 21 with how the return is defined (maybe adding self.) but I'm not sure please let me know if the problem is on my end, thank you.

**To Reproduce**
marketplace_id = ['ATVPDKIKX0DER']
eleg = FbaInboundEligibility(credentials=credentials).get_item_eligibility_preview(marketplace_id,"asin","INBOUND")
print(eleg)

API Response was expected

 - OS: [Windows]

**Error Message**

TypeError                                 Traceback (most recent call last)
<ipython-input-10-9af74e6c9c15> in <module>
      1 marketplace_id = ['ATVPDKIKX0DER']
----> 2 eleg = FbaInboundEligibility(credentials=credentials).get_item_eligibility_preview(marketplace_id,"asin","INBOUND")
      3 print(eleg)

~\anaconda3\lib\site-packages\sp_api\base\helpers.py in wrapper(*args, **kwargs)
     19                 'method': method
     20             })
---> 21             return function(*args, **kwargs)
     22         wrapper.__doc__ = function.__doc__
     23         return wrapper

TypeError: get_item_eligibility_preview() takes 1 positional argument but 4 were given

**Comment by saleweaver** [comment]
You're passing arguments to a function that doesn't take args but kwargs. Please have a look at the documentation.
