### ISSUE TITLE
get_authorization_code needs to be a grantless operation

### ISSUE THREAD

**Issue by BookLaugh** [saleweaver/python-amazon-sp-api#193]
**Which API - Endpoint is your request about.**
Authorization API, endpoint: /authorization/v1/authorizationCode
Method `get_authorization_code()`

**Additional context**

According to SP-API docs, get_authorization_code in Authorization API is a grantless operation, while in python-amazon-sp-api it is not.

See: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#grantless-operations

Also: This operation requires different scope than one used in Notifications API, so AccessTokenClient needs to support more than one scope value for grantless data. In consequence - `grantless_cache` needs to use scope value (or token flavor in general) as a part of cache key, because tokens for different scopes will have different values and can't be used interchangeably.

**Comment by saleweaver** [comment]
Thanks! I've merged the pr
