### ISSUE TITLE
six~=1.15.0 in setup.py

### ISSUE THREAD

**Issue by pavelion** [saleweaver/python-amazon-sp-api#198]
Is there any reason to depend on six ~= 1.15.0 ? Latest version is 1.16.0, it is backwards compatible with 1.15.0 and the way dependency is specified in setup.py prohibits to use python-amazon-sp-api in projects with the latest six library.

**Comment by saleweaver** [comment]
You're describing a pull request but created an issue. Why?

**Comment by pavelion** [comment]
OK, will do.
