### ISSUE TITLE
"List/Array" parameters in FulfillmentInbound only return an API response with the last item in the list not all of them.

### ISSUE THREAD

**Issue by DavidRHid** [saleweaver/python-amazon-sp-api#201]
When passing lists as parameters (at least in FulfillmentInbound ) I've found that the API only returns the last value submitted instead of a list that corresponds to what I submitted. This may be a problem on my end but I've tried debugging as much as possible and everything seems to lead back here. Alternately maybe Amazon can only process one at a time but then why would the functions accept list values? If this isn't a bug sorry for the bother but if it is I hope we can improve the code and help others. Thanks 

**To Reproduce**
res = FulfillmentInbound().prep_instruction({"ShipToCountryCode": "US", "SellerSKUList": ["SKU2", "SKU1"]})
print(res)
#same thing happens with ASIN lists here 

**Expected behavior**
API response that contains results for both SKU1 and SKU2

 - OS: [Windows]

Thank You

**Comment by saleweaver** [comment]
please join to a string, ','.join(['SKU1', 'SKU2']) this behavior will change in the upcoming release of v1
