### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by splurring** [saleweaver/python-amazon-sp-api#208]
I am having an issue with authentication. This is my code:

```
from sp_api.api import Orders
from sp_api.api import Reports
from sp_api.api import Feeds
from sp_api.base import SellingApiException
from sp_api.base.reportTypes import ReportType
from datetime import datetime, timedelta

credentials = dict(
    refresh_token='Atzr|XXX,
    lwa_app_id='amzn1.application-oa2-client.XXXX',
    lwa_client_secret='9287bXXX',
    aws_secret_key='AKXXX',
    aws_access_key='BAWXXX',
    role_arn='arn:aws:iam::45XXX:role/XXX'
)

try:
    res = Orders(credentials=credentials).get_orders(CreatedAfter=(
        datetime.utcnow() - timedelta(days=7)).isoformat())
    print(res.payload)  # json data
except SellingApiException as ex:
    print(ex)
```

And I get the error 

`botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.`

I believe I followed through the steps that if said on the github, so please let me know if there is a solution.

**Comment by saleweaver** [comment]
There are multiple threads about Authentication problems in the discussions.

**Comment by rohitdobariya** [comment]
@saleweaver I am getting the same error can you please let me know what is the issue and which threads this issue discussion?

**Comment by MrJamesFeng** [comment]
i'm having the same issue, how have you solved this problem please?
