### ISSUE TITLE
Notifications().create_destination does not work for event_bridge

### ISSUE THREAD

**Issue by DanielLanger** [saleweaver/python-amazon-sp-api#209]
**Describe the bug**
Amazon has two channels for notifications: sqs and eventbridge (https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md) the create_destination method (https://github.com/saleweaver/python-amazon-sp-api/blob/2269ddd1497cb867a3e70018d0d3da51e594b98e/sp_api/api/notifications/notifications.py#L115) only works for sqs. The schema for the eventBridge resourceSpecification can be found here https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#eventbridgeresource

**To Reproduce**

Try calling Notifications.create_destination() for an eventBridge resource

**Expected behavior**

You should be able to pass in either an sqs ARN or the specified eventBridge resourceSpecification and successfully create a destination

**Desktop (please complete the following information):**

 - OS: [e.g. Linux/**Mac**/Windows]

**Additional context**

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/commit/63bd6bbb234b7048eba7432d703fc0187594ded7

**Comment by DanielLanger** [comment]
@saleweaver left a comment, might be a typo for cachetools verisoning "cachetools>=4.2.0,<2". I'm unable to upgrade, i get this error  Could not find a version that satisfies the requirement cachetools<2,>=4.2.0
