### ISSUE TITLE
Add functionality to switch credentials inside of a program

### ISSUE THREAD

**Issue by DavidRHid** [saleweaver/python-amazon-sp-api#211]
Right now I don't think it's possible to switch out one set of credentials for another while running the program as if "account" is set to new credentials, "SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]" is always thrown. Is there any way to clear the variables when switching over credentials so that the program allows the switch? 
Thanks!

To replicate
`x = Orders(account="AccountOne").get_orders(CreatedAfter=(dt.utcnow() - timedelta(days=7)).isoformat())

print(x)

y = Orders(account="AccountTwo").get_orders(CreatedAfter=(dt.utcnow() - timedelta(days=7)).isoformat())

print(y)`

**Comment by saleweaver** [comment]
Allowing this is not currently planned

**Comment by DavidRHid** [comment]
> Allowing this is not currently planned

Is there any way to fix this from the code? Can't seem to find where the variables are stored or how to clear them.
Thank you
