### ISSUE TITLE
fba-inventory-api not found on the documentation for available endpoints

### ISSUE THREAD

**Issue by ykuni-software-developer** [saleweaver/python-amazon-sp-api#213]
Hello,
I have encountered your <a href="https://python-amazon-sp-api.readthedocs.io/en/v0.6.4/endpoints/"> documentation </a>. From the list of endpoints in the documentation there is no fba-inventory-api which was recently listed in the <a href="https://github.com/amzn/selling-partner-api-docs/tree/main/references"> selling-partner-api-docs </a> as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/78894093/127887927-0e0fb006-e790-42a9-b59b-f246f4c49950.png)
I would like to clarify if the fba-inventory-api endpoint is available in your library even if it was not shown in the documentation?

**Comment by saleweaver** [comment]
Seems to be missing in the docs, will add that. The client for fba inventories is called Inventories.
