### ISSUE TITLE
feed api

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#214]
how can it be possible that the same feed request having the same enum "POST_ORDER_FULFILLMENT_DATA" having two different refresh tokens give two different responses 
1st response is correct and it gives me the output
2nd response is  giving me error `[{'code': 'InvalidInput', 'message': 'Invalid request parameters', 'details': ''}]`
but refresh token is valid?????

**Comment by saleweaver** [comment]
I don't understand what you're trying to do. Please ask questions in discussions.
