### ISSUE TITLE
Inventory summeries

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#22]
https://github.com/saleweaver/python-amazon-sp-api/pull/21
I added a new api to get the inventory summaries, would be great if u can merge it please :)

**Comment by saleweaver** [comment]
Meged, thanks again!

**Comment by saleweaver** [comment]
Hi,

do you have strange skus to test against? 

For me, skus containing an apostrophe or spaces don't yield results with this endpoint. I've since encoded them in the last commit (before it was failing the request), but there are no results. Do you have an idea?

**Comment by mohamedfawzy96** [comment]
No didn't really test this case, but if I find something will let you know.

**Comment by saleweaver** [comment]
I've already filed a bug report with amazon, I don't think the wrapper can do something about it atm
