### ISSUE TITLE
Orders.get_orders(AmazonOrderIds=[str]) is confusing

### ISSUE THREAD

**Issue by sinancetinkaya** [saleweaver/python-amazon-sp-api#224]
Hi, in the docs it's said that: AmazonOrderIds=['XXX-XXXXXX-XXXXXXX', 'XXX-XXXXXX-XXXXXXX', 'XXX-XXXXXX-XXXXXXX']
However response.payload has only the last Amazon Order ID's result.
This format works fine: AmazonOrderIds='XXX-XXXXXX-XXXXXXX,XXX-XXXXXX-XXXXXXX,XXX-XXXXXX-XXXXXXX'

I don't know if it's a bug in the code or a missing info in the docs.

Thanks

**Comment by saleweaver** [comment]
Thanks for reporting. Yes it is, this will change for all endpoints in one of the next releases.
