### ISSUE TITLE
How to use restrictedDataToken in Orders().get_orders() ?

### ISSUE THREAD

**Issue by sinancetinkaya** [saleweaver/python-amazon-sp-api#225]
I have created `restrictedDataToken` according to this guide https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-buyer-and-shipping-address-information-for-bulk-orders
```python
body = {
    "restrictedResources": [
        {
            "method": "GET",
            "path": "/orders/v0/orders",
            "dataElements": ["buyerInfo", "shippingAddress"]
        }
    ]
}

tokens_api = Tokens(credentials=credentials)
response = tokens_api.create_restricted_data_token(restrictedResources=body)
restrictedDataToken = response.payload['restrictedDataToken']
```
But I don't know how to use `restrictedDataToken` in Orders() endpoint

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/discussions/207

**Comment by sinancetinkaya** [comment]
I'm able to get PII info in orders from Orders endpoint myself using boto3.

**Comment by sinancetinkaya** [comment]
The code below works fine. Please consider adding headers (or better way you think of) in the endpoints

```python
from sp_api.api import Orders, Tokens
from sp_api.base import ApiResponse, sp_endpoint

class MyOrders(Orders):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @sp_endpoint('/orders/v0/orders')
    def get_orders(self, **kwargs) -> ApiResponse:
        headers = kwargs.pop('headers') if 'headers' in kwargs else None
        return self._request(kwargs.pop('path'), params={**kwargs}, headers=headers)


credentials = {...}
AmazonOrderIds = [...]

tokens_api = Tokens(credentials=credentials)
response = tokens_api.create_restricted_data_token(
    restrictedResources=[
        {
            "method": "GET",
            "path": "/orders/v0/orders",
            "dataElements": ["buyerInfo", "shippingAddress"]
        }
    ]
)
restrictedDataToken = response.payload['restrictedDataToken']

orders_api = MyOrders(credentials=credentials)

response = orders_api.get_orders(
    AmazonOrderIds=",".join(AmazonOrderIds),
    headers={'x-amz-access-token': restrictedDataToken}
)
```

**Comment by paulabirocchi** [comment]
@sinancetinkaya  can you please describe which informations you used in the credentials?

**Comment by sinancetinkaya** [comment]
> @sinancetinkaya can you please describe which informations you used in the credentials?

I followed Amazon selling partner API guide to create credentials. That's a long guide. You need to follow each step carefully.

**Comment by LuisB2904** [comment]
With the code from @sinancetinkaya i get this error:

sp_api.base.exceptions.SellingApiServerException: [{'message': 'We encountered an internal error. Please try again.', 'code': 'InternalFailure'}]

does someone have the same error?

**Comment by bjquinn** [comment]
Thank you @sinancetinkaya, that worked for me.  Surely there's got to be a better way to do this from within the library itself without having to manually hack the RDT token in the headers like that?
