### ISSUE TITLE
'Access token is missing in the request header.'

### ISSUE THREAD

**Issue by fkhjoy** [saleweaver/python-amazon-sp-api#23]
Could you please tell me why I am getting this error?
![Screenshot from 2021-01-30 00-47-59](https://user-images.githubusercontent.com/25137428/106317158-16ae3a00-6298-11eb-85d4-2017cd04d028.png)

**Comment by saleweaver** [comment]
Hello again,
I can't tell you why you are getting this error without seeing your code. Please follow the bug template and provide context, then I'll be glad to take a look.

**Comment by fkhjoy** [comment]
> Hello again,
> I can't tell you why you are getting this error without seeing your code. Please follow the bug template and provide context, then I'll be glad to take a look.
Thank You. I was using the below code

from datetime import datetime, timedelta
from sp_api.api import Orders
from sp_api.base import SellingApiException
credentials= dict(
        refresh_token='XXXXX',
        lwa_app_id='XXXXX',
        lwa_client_secret='XXXXX',
        aws_secret_key='kXXXXXXXXXXXXXXXXX3',
        aws_access_key='AXXXXXXXXXXX2',
        role_arn='arn:aws:iam::XXXXXXXXX:role/SellingPartnerApi',
    )
Orders(credentials=credentials).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())

**Comment by saleweaver** [comment]
My best guess is that your refresh token is invalid

**Comment by fkhjoy** [comment]
> My best guess is that your refresh token is invalid.
> 
> After further investigating, at least one of the 3 is invalid
> 
>     * refresh_token
> 
>     * lwa_app_id
> 
>     * lwa_client_secret

Thank You.
I am checking on to it.

**Comment by fkhjoy** [comment]
![Screenshot from 2021-02-07 01-13-14](https://user-images.githubusercontent.com/25137428/107127659-c6f7f000-68e1-11eb-9bc3-e9832c96c6eb.png)

Could you please tell me about this error?
Are the setup ok or wrong?
