### ISSUE TITLE
Shipment data

### ISSUE THREAD

**Issue by manibha-jain** [saleweaver/python-amazon-sp-api#231]
**Which API - Endpoint is your request about.**
Shipment

**A clear and concise description of what you want to happen..**

I do not see any shipment listing. Neither am i getting parameter of shipment id in orders api. What should happen is i must get the shipment id  from the order and i should be able to fetch details about that shipment from the existing shipment api.

**Comment by saleweaver** [comment]
There's no Shipment API endpoint, and there are no shipment ids returned from any order api endpoint. I think you're mixing something up here. Please be specific and link to the respective endpoint's client. Please ask questions in discussions.

**Comment by maonogit** [comment]
How to use parameter "ShipmentStatusList"。When I use API "/fba/inbound/v0/shipments".
