### ISSUE TITLE
get_shipment function returns error

### ISSUE THREAD

**Issue by manibha-jain** [saleweaver/python-amazon-sp-api#233]
**Describe the bug**
get_shipment function returns an error with a valid shipment id.I copied the shipment id from Inventory-> Manage FBA shipments  in amazon seller account.
It displays the error [{'code': 'InternalFailure', 'message': 'We encountered an internal error. Please try again.', 'details': ''}]

**To Reproduce**

This is the way i called the function. 
from sp_api.api import Feeds,Shipping,Catalog,Finances,Shipping
Shipping(credentials=credentials,marketplace=Marketplaces.IN).get_shipment(shipmentId='FBAXXXXXXXXX')

**Comment by saleweaver** [comment]
The error message pops up in sandbox usually.
