### ISSUE TITLE
FulfillmentInbound

### ISSUE THREAD

**Issue by manibha-jain** [saleweaver/python-amazon-sp-api#235]
**Describe the bug**

get_shipments is not working properly. When i used only status "CLOSED" in **ShipmentStatusList** then some data is returned but when i used "SHIPPED" status with it, then no data is returned. Why the shipments with closed status are not returned if no shipped data is there?

**To Reproduce**

Try the **FulfillmentInbound** first with status you know will have data.In my case it was "CLOSED" .

`FulfillmentInbound(credentials=credentials,marketplace=Marketplaces.IN).get_shipments(QueryType=["SHIPMENT"],ShipmentStatusList=["CLOSED"])`

this returns data.

Then try same query but with adding a status that has no data "SHIPPED".
`
FulfillmentInbound(credentials=credentials,marketplace=Marketplaces.IN).get_shipments(QueryType=["SHIPMENT"],ShipmentStatusList=["CLOSED","SHIPPED"])`

this returns no data.

**Expected behavior**

It should return data for both the shipment status.

**Comment by saleweaver** [comment]
",".join(shipment_status_list). 

Please ask questions in discussions, issues will be closed unanswered.

**Comment by manibha-jain** [comment]
But @saleweaver  it is an issue with the API.
