### ISSUE TITLE
Error with multiple credentials

### ISSUE THREAD

**Issue by rusanpas** [saleweaver/python-amazon-sp-api#252]
**Describe the bug**

When you have multiple sp-api credentials, and you use them alternately, the error "Access requested resource is denied" appears

**To Reproduce**

In my case, I have a lambda that is invoked with different credentials. When it does a coldstart it works fine, but when it doesn't, and you change credentials, it causes the error "Access requested resource is denied".

**Expected behavior**

A valid response from the api call

**Additional context**

I think the reason for the failure is the role cache, which by using the same key causes overlap. If I do role_cache.clear () on every invocation it works fine.

The "role" key should change with each credential, like the other caches (access_token, grantless).

```   
    def set_role(self):
        role = self.boto3_client.assume_role(
            RoleArn=self.credentials.role_arn,
            RoleSessionName='guid'
        )
        role_cache['role'] = role
        return role

   @property
    def role(self):
        try:
            role = role_cache['role']
        except KeyError:
            role = self.set_role()
        return role.get('Credentials')
```

**Comment by saleweaver** [comment]
Do you want to create a pull request for that or should I?

**Comment by rusanpas** [comment]
Include pull request #253 with fix
