### ISSUE TITLE
Issue with "GZIP" compression in Reports API

### ISSUE THREAD

**Issue by jakerator** [saleweaver/python-amazon-sp-api#26]
**Describe the bug**
When Reports API returns gzipped document, it looks like content is corrupted. 

**To Reproduce**

when the report document is too big, it adds gzip compression. But then can't open that archive...
Reports().create_report(reportType='GET_XML_BROWSE_TREE_DATA')

**Expected behavior**

Maybe need to gunzip first and then AES-decode? Or maybe just a bug with AES decoder...

**Desktop (please complete the following information):**

 - Ubuntu

**Comment by saleweaver** [comment]
Thanks for bringing this up, didn't have this popup in reports yet. It's implemented in feeds, do you mind to create a pull request?

Here's the feeds implementation:

```
        response = GetFeedDocumentResponse(
            **self._request(fill_query_params(kwargs.pop('path'), feed_id), params=kwargs,
                            add_marketplace=False).json())
        url = response.payload.get('url')
        decrypted = decrypt_aes(
            requests.get(url).content,
            response.payload.get('encryptionDetails').get('key'),
            response.payload.get('encryptionDetails').get('initializationVector')
        )

        if 'compressionAlgorithm' in response.payload:
            return zlib.decompress(bytearray(decrypted), 15 + 32).decode('iso-8859-1')
        return decrypted.decode('iso-8859-1')

```

should be fairly simple, but I have other work to do the next few days.
