### ISSUE TITLE
UnicodeEncodeError when downloading/decrypting using Reports().get_report_document()

### ISSUE THREAD

**Issue by Guerri114** [saleweaver/python-amazon-sp-api#271]
**Describe the bug**
Python throws a UnicodeEncodeError exception when using Reports().get_report_document().

**To Reproduce**
```
# report request
createReportResponse = Reports(credentials=credentials
    ,marketplace=marketplaces.Marketplaces.CA).create_report(
        reportType="GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
        reportOptions={"reportPeriod": "WEEK"},
        dataStartTime="2021-10-03",
        dataEndTime="2021-10-09"
        )

# report id
report_id = createReportResponse.payload['reportId']
print("Report ID: ", report_id)

# get report (loop)
getReportResponse = Reports(credentials=credentials, marketplace=marketplaces.Marketplaces.CA).get_report(report_id=report_id)
while getReportResponse.payload['processingStatus'] != 'DONE':
    print("Report status is: %s. Sleeping for 10 seconds..." % getReportResponse.payload['processingStatus'])
    time.sleep(10)
    getReportResponse = Reports(credentials=credentials, marketplace=marketplaces.Marketplaces.CA).get_report(report_id=report_id)

# report document id
report_document_id = getReportResponse.payload['reportDocumentId']
print("Report document ID: ", report_document_id)

# create filename
output_file = report_document_id + ".json"

# get report document
getReportDocumentResponse = Reports(credentials=credentials,
    marketplace=marketplaces.Marketplaces.CA).get_report_document(
        document_id=report_document_id,
        decrypt=True,
        file=output_file,
        character_code='utf-8'
        )
```

**Expected behavior**
Report download, decrypts, and decompresses without throwing an exception.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I've tried specifying different values for `character_code` such as `iso-8859-1` but I still get an exception.

**Comment by saleweaver** [comment]
Can you please download the report without decrypting it and check it? Is the data in the report confidential, or can you share it?

**Comment by Guerri114** [comment]
The report is confidential so I cannot share it.

What should I check now that I've downloaded the report?

Thanks in advance for your help!

Also, why doesn't `python-amazon-sp-api` use the `2021-06-30' version of the SP-API for Reports which removes the need to decrypt reports?

**Comment by Guerri114** [comment]
I'm pretty sure I found the issue here: https://github.com/saleweaver/python-amazon-sp-api/blob/79a7e0b12052982cc49652c3e5693684ceaaa78b/sp_api/api/reports/reports.py#L116

Proposed change:
```python
with open(file, "w", encoding=character_code) as text_file:
```

**Comment by Guerri114** [comment]
FYI: https://github.com/saleweaver/python-amazon-sp-api/pull/272

**Comment by saleweaver** [comment]
Thanks, that should fix it. 
I'll generate the code for the new versions the next few days, encryption can be removed for Feeds as well.

**Comment by Guerri114** [comment]
Thanks.

How would a developer use `pip` to pull the latest version of `reports.py`?

**Comment by saleweaver** [comment]
> Thanks.
> 
> How would a developer use `pip` to pull the latest version of `reports.py`?

You mean https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github?

**Comment by Guerri114** [comment]
I was more looking for how to pull the most up-to-date version of a package. When I tried the normal method (i.e. `pip install python-amazon-sp-api --upgrade`) I didn't get the latest version of the `reports.py` file.

**Comment by saleweaver** [comment]
> I was more looking for how to pull the most up-to-date version of a package. When I tried the normal method (i.e. `pip install python-amazon-sp-api --upgrade`) I didn't get the latest version of the `reports.py` file.

Yeah, I haven't released yet. I'll push a release in a minute, you should be able to download using pip in a couple of minutes. 

What you want to do is described in the stackoverflow answer, that would get you any state of the package you want, e.g. latest.

**Comment by Guerri114** [comment]
got it. Thanks!

**Comment by saleweaver** [comment]
I've pushed a version with the new client `ReportsV2` if you want to try it.
