### ISSUE TITLE
Should I make pull request for making role ARN optional

### ISSUE THREAD

**Issue by dorian-i** [saleweaver/python-amazon-sp-api#279]
Hi @saleweaver 

**Which API - Endpoint is your request about.**

All of them.

**A clear and concise description of what you want to happen.**

We can make requests without needing ARN role like explained here https://github.com/saleweaver/python-amazon-sp-api/issues/11#issuecomment-770115130. 

Can I make a pull request so "assume_role()" is optional and providing the ability to make requests without it ?

**Comment by saleweaver** [comment]
Hey, yeah that would be great. I'm currently working on the client and authorization, I can use that for the next version then.

**Comment by ddorian** [comment]
@saleweaver a simple pull request https://github.com/saleweaver/python-amazon-sp-api/pull/280

**Comment by saleweaver** [comment]
#280
