### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by JonhSilver** [saleweaver/python-amazon-sp-api#285]
from sp_api.api import Orders
from sp_api.api import Reports
from sp_api.api import Feeds
from sp_api.base import SellingApiException
from sp_api.base.reportTypes import ReportType
from datetime import datetime, timedelta

credentials=dict(
        refresh_token='Atzr|..',
        lwa_app_id='amzn1.application-oa2-client.1....',
        lwa_client_secret='359ae39..',
        aws_secret_key='+VUx2...',
        aws_access_key='AKIAZI....',
        role_arn='arn:aws:iam::635:role/Selling_Partner',
    )
# orders API
try:
    res = Orders(credentials=credentials).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
    print(res.payload)  # json data
except SellingApiException as ex:
    print(ex)

Response

[{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]
Traceback (most recent call last):
  File "C:\Users\Desktop\PBI\Amazon.py", line 25, in <module>
    createReportResponse = Reports(credentials=credentials).create_report(reportType=ReportType.GET_MERCHANT_LISTINGS_ALL_DATA)
  File "C:\Python3\lib\site-packages\sp_api\base\helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "C:\Python3\lib\site-packages\sp_api\api\reports\reports.py", line 41, in create_report
    return self._request(kwargs.pop('path'), data=kwargs)
  File "C:\Python3\lib\site-packages\sp_api\base\client.py", line 117, in _request
    return self._check_response(res)
  File "C:\Python3\lib\site-packages\sp_api\base\client.py", line 124, in _check_response
    raise exception(error, headers=res.headers)
sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

what im doing wrong?

All credentials is working!!!

and how to set marketplaceid?

**Comment by saleweaver** [comment]
https://python-amazon-sp-api.readthedocs.io/en/latest/client_usage/
