### ISSUE TITLE
role_arn is required

### ISSUE THREAD

**Issue by ilyasProgrammer** [saleweaver/python-amazon-sp-api#290]
Starting from this version role_arn is required and i cant pull data using arn user. Before i could remove role_arn line from config file and it makes lib use arn user.

**Comment by saleweaver** [comment]
Sorry my bad, that was an accident, 0.8.3 fixes this in a minute

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/releases/tag/v0.8.3
