### ISSUE TITLE
How to contribute :)

### ISSUE THREAD

**Issue by alex-goat** [saleweaver/python-amazon-sp-api#3]
Hi Michael,
kann man dich mit Test Ergebnissen aus dem FBA Alltag unterstützen?
Mir ist gerade noch nicht ganz klar wie man die library einbinden soll aber wenn ich mir den weg durch den IAM Dschungel dadurch ersparen kann helfe ich gerne mit die Entwicklung voran zu treiben.

**Comment by saleweaver** [comment]
Hi Alex, 
das wäre klasse, da gibt es noch einiges zu tun und FBA wollte ich als nächstes ohnehin beginnen. Die schlechte Nachricht ist das du trotzdem den IAM Nutzer brauchst, danach werden die Calls aber sehr einfach gemacht. Die ganze Signierung von Nachrichten usw. in der lib ist stable. Sag mir Bescheid wenn du fertig bist, am einfachsten ist der Create Report call, dazu musst du nur die Anweisungen der readme befolgen..
