### ISSUE TITLE
ShipmentStatusList required

### ISSUE THREAD

**Issue by ilyasProgrammer** [saleweaver/python-amazon-sp-api#303]
Hi. When calling this method:
https://github.com/saleweaver/python-amazon-sp-api/blob/a595f4287cb6ee6c9c10c275814d31ce65520403/sp_api/api/fulfillment_inbound/fulfillment_inbound.py#L298
got this error:
{SellingApiBadRequestException}[{'code': 'InvalidInput', 'message': 'At least one of ShipmentStatusList and ShipmentIdList must be provided', 'details': ''}]
So correct call should look like:
`inbound_api.get_shipments(QueryType='SHIPMENT', **{"ShipmentStatusList": "WORKING"})`
Perhaps ShipmentStatusList should be the mandatory method attribute.

**Comment by saleweaver** [comment]
No it shouldn't. You either pass that, or a list of ids. Or a last updated date range for the date_range query type. The endpoint is horribly designed by Amazon, but all of the parameters are optional.
