### ISSUE TITLE
Inventories sellerSkus array only works with no spaces

### ISSUE THREAD

**Issue by Uzejo** [saleweaver/python-amazon-sp-api#306]
The sellerSkus option in the Inventories class seems to only work correctly if the seller SKU has no spaces in it.

for example:

foo = Inventories().get_inventory_summary_marketplace(sellerSkus = ["SKU_1", "SKU_2"])

will work fine

foo = Inventories().get_inventory_summary_marketplace(sellerSkus = ["S K U_1", "SKU 2"])

will return nothing

foo = Inventories().get_inventory_summary_marketplace(sellerSkus = ["SKU_1", "S K U _2"])

will return SKU_1

I would just update the SKU's in amazon but apparently you can't do that without recreating the listing.

**Comment by saleweaver** [comment]
I thought I had fixed that some time ago, but that seems to pop up every now and then again. Id recommend not using spaces in SKUs, nothing but problems.
