### ISSUE TITLE
FulfillmentInbound QueryType DATE_RANGE

### ISSUE THREAD

**Issue by ilyasProgrammer** [saleweaver/python-amazon-sp-api#307]
Hi. Im struggling with inbound shipments. When i trying to get it like this:
`        
inbound_api = FulfillmentInbound(Marketplaces[mp.code], refresh_token=mp.api_refresh_token)
inbound_api.get_shipments(QueryType='DATE_RANGE', LastUpdatedAfter="2021-11-01T00:00:00.001Z", LastUpdatedBefore="2021-12-15T00:00:00.001Z")`

im getting error:
`{SellingApiBadRequestException}[{'code': 'InvalidInput', 'message': 'At least one of ShipmentStatusList and ShipmentIdList must be provided', 'details': ''}]`

Also i tried to get it using QueryType='SHIPMENT'  and providing ShipmentStatusList. As result always get empty data in response.
I've tried all statuses ['WORKING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'CHECKED_IN', 'RECEIVING', 'CLOSED', 'CANCELLED', 'DELETED', 'ERROR']

**Comment by saleweaver** [comment]
```
        last_updated_after = (datetime.utcnow() - timedelta(days=10))
        res = FulfillmentInbound(marketplace=Marketplaces.DE).get_shipments(
            QueryType='DATE_RANGE',
            LastUpdatedAfter=last_updated_after.isoformat(),
            LastUpdatedBefore=datetime.utcnow().isoformat(),
            ShipmentStatusList=','.join([
                'WORKING', 'SHIPPED', 'RECEIVING',
                'CANCELLED', 'DELETED',
                'CLOSED', 'ERROR', 'IN_TRANSIT',
                'DELIVERED',
                'CHECKED_IN'
            ]))

**Comment by saleweaver** [comment]
Should you wonder why some shipments are returned, please give this issue a thumbs up:
https://github.com/amzn/selling-partner-api-docs/issues/1716
