### ISSUE TITLE
Call api by access token

### ISSUE THREAD

**Issue by One2r** [saleweaver/python-amazon-sp-api#308]
**Which API - Endpoint is your request about.**

All api

**Additional context**

The project call api by refresh token ,and cache access token in TTLCache.
Because I have access token in another project,so I do not have to manage access token.
So is any way can I call api by access token?

**Comment by saleweaver** [comment]
Currently there is not. If you want to create a pull request, please do so!

**Comment by saleweaver** [comment]
Hm, actually there is. Can you try to pass the access token via 'restricted_data_token' to the client
