### ISSUE TITLE
Missing getReports

### ISSUE THREAD

**Issue by vincmarc** [saleweaver/python-amazon-sp-api#31]
Hi, I would find useful to have the operation getReports (Endpoint: GET /reports/2020-09-04/reports), https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreports

Basically you get a list of reports that meet the specifications you have given

Do you think is feasible?

**Comment by saleweaver** [comment]
#32 

I've create a discussion topic for the endpoint, this one is on the todo list and will be implemented in the next update

**Comment by saleweaver** [comment]
Hi @vincmarc,

did you try the endpoint and does it work?

**Comment by vincmarc** [comment]
Hi @saleweaver yes, it's perfectly working! Thanks
