### ISSUE TITLE
@load_all_pages() decorator does not work

### ISSUE THREAD

**Issue by hrausch** [saleweaver/python-amazon-sp-api#310]
**Describe the bug**
When I defined a function to get inventory summary with the decorator, the generator did not call the other page even when response has the nextToken pagination.
**To Reproduce**

@throttle_retry()
@load_all_pages()
def load_all_inventory(**kwargs):
    return Inventories().get_inventory_summary_marketplace(**kwargs)

for page in load_all_inventory(details=False):
    print(page.pagination)

**Expected behavior**

The function load_all_inventory returns all pages considering the nextToken.

**Desktop (please complete the following information):**

MAC

**Additional context**

API returns only the first page.

**Comment by saleweaver** [comment]
Hi, 

the `load_all_pages` decorator takes `next_token_param` as an input. 
It's explained at the bottom of this page: https://sp-api-docs.saleweaver.com/utils/load_all_pages/

Unfortunately, Amazon doesn't follow naming conventions. The next token parameter is sometimes called NextToken, next_token, or nextToken like in you example.

To make the decorator work for inventories, simply follow the doc's advice and pass the name to it. 

```
@load_all_pages(next_token_param='nextToken')
```

**Comment by hrausch** [comment]
Hello guys,

The problem persists even next_token_param. I think this parameter will be used on the next request. However, the problem is in getting the token from the response.

I have made a change on ApiResponse.py (line 48) and it worked. I didn't performed unit test to check side-effects.

Please, see below the modification.

self.next_token = (
                nextToken
                or self.payload.get("NextToken", None)
                or self.pagination.get("nextToken", None)
            )

**Comment by saleweaver** [comment]
Sorry, I just saw it. I actually was thinking it would make sense to alter the behavior and always find it in ApiResponse. I'll make some changes tomorrow and push them. Do you want to create a pull request for the pagination?

**Comment by hrausch** [comment]
Yes,I've created the pull request to your develop branch.

**Comment by saleweaver** [comment]
Thank you, I've merged it into master. I'll add a release the next couple of days.
