### ISSUE TITLE
Login with amazon

### ISSUE THREAD

**Issue by Green5tar** [saleweaver/python-amazon-sp-api#312]
Hello. I am trying to get access for my clients.
When I make Login With Amazon request i received a "selling_partner_id" and "spapi_oauth_code".
Next request is goes for refresh token thet we are going to use in future request
authorize_auth_code(spapi_oauth_code)
In next requests I need to pu credentials

credentials = dict(
            refresh_token="Some token",
            lwa_app_id=os.environ.get('LWA_CLIENT_ID'),
            lwa_client_secret=os.environ.get('LWA_CLIENT_SECRET'),
            aws_access_key="",
            aws_secret_key="",
            role_arn=os.environ.get('SP_API_ROLE_ARN')
        )

Where I can get "aws_access_key" and "aws_secret_key" from client if amazon not send it to me after login, or it's mut be from iam (not received from user)?

And why do we need "selling_partner_id"?

**Comment by saleweaver** [comment]
Please ask questions in discussions. Thanks!
