### ISSUE TITLE
Error when downloading file from Reports 

### ISSUE THREAD

**Issue by matt-behrens-1** [saleweaver/python-amazon-sp-api#320]
**Describe the bug**
Can't download the file due to filename being passed into Reports().get_report_document being a str of the relative filepath and not file. 

"AttributeError: 'str' object has no attribute 'write'". 

**To Reproduce**
1. Creating Report
`Reports(marketplace=Marketplaces.US).create_report(reportType=ReportType.GET_VENDOR_INVENTORY_HEALTH_AND_PLANNING, dataStartTime=startDate, dataEndTime=endDate)`

2. Getting Report Status
`Reports(marketplace=Marketplaces.US).get_report(response.payload['reportId'])`

3. Downloading Report
`Reports(marketplace=Marketplaces.US).get_report_document(statusResponse.payload['reportDocumentId'], decrypt=True, file=filename)`

**Expected behavior**

The report should be downloaded to relative filepath.

**Desktop (please complete the following information):**

 - OS: Linux

**Additional context**

Used to work in older version of Reports, with this logic. 

```
if file:
  if isinstance(file, str):
      with open(file, "w", encoding=character_code) as text_file:
          text_file.write(document)
  else:
      file.write(document)
```

**Comment by saleweaver** [comment]
Thanks! I've added it again
