### ISSUE TITLE
get_feeds not found in Feeds

### ISSUE THREAD

**Issue by ZhuFanCheng** [saleweaver/python-amazon-sp-api#323]
**Describe the bug**
Getting "'Feeds' object has no attribute 'get_feeds'" error when trying to use the get_feeds method. 

**To Reproduce**

from sp-api import Feeds
Feeds(credentials, marketplace).get_feeds()
(output: error)

**Expected behavior**

Expected to see list of feeds.

**Desktop (please complete the following information):**

 - OS: MacOS / Monterey

**Comment by saleweaver** [comment]
The client has a get_feeds method. Guessing from your code, the error is either the import, which would be from sp_api.api import Feeds, or the way you initialize the client, which needs to be Feeds(marketplace, credentials=credentials)
