### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation

### ISSUE THREAD

**Issue by neatokara** [saleweaver/python-amazon-sp-api#324]
I am receiving this error when attempting to use Reports :
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: {arn} is not authorized to perform: sts:AssumeRole on resource: {arn} 

It looks like there was a similar issue in the past, where the solution was to remove the policy, however I cannot do this as I have another application that is using the native AWS signing code to access sp api. Are there any other work arounds?

**Comment by saleweaver** [comment]
Hi,

one of the two options should still work. Please try it with and without role_arn, if the error persists please share code that demonstrates the issue. Thanks.

**Comment by neatokara** [comment]
I've tried that way and I get:
TypeError: __init__() missing 1 required positional argument: 'role_arn'

**Comment by saleweaver** [comment]
Then you're using an old version

**Comment by neatokara** [comment]
I certainly was. Thank you so much!
