### ISSUE TITLE
Unauthorized access

### ISSUE THREAD

**Issue by eternalparquet** [saleweaver/python-amazon-sp-api#343]
**Describe the bug**
When I try to access to the api I get an error.
request an api.

Excptected:
response from the requested api.

I get this error: sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]
I followed carefully the steps to create a iam user and role here: 
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/discussions/305

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/discussions/322

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/discussions/326
