### ISSUE TITLE
Sales().get_order_metrics error

### ISSUE THREAD

**Issue by AnsonHwang86** [saleweaver/python-amazon-sp-api#353]
```
res = Sales().get_order_metrics("2020-10-01T00:00:00-07:00--2020-11-01T20:00:00-07:00", Granularity.MONTH)
print(res)
```

hello, when I run the code above, there will print(return) an error show as following. It seem as a regex matching error. 

Traceback (most recent call last):
  File "C:/Users/DELL SERVER/PycharmProjects/ScrapeAE/SPAPI.py", line 39, in <module>
    res = Sales().get_order_metrics("2020-10-01T00:00:00-07:00--2020-10-01T20:00:00-07:00", Granularity.MONTH)
  File "C:\Users\DELL SERVER\PycharmProjects\ScrapeAE\venv\lib\site-packages\sp_api\base\helpers.py", line 20, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\DELL SERVER\PycharmProjects\ScrapeAE\venv\lib\site-packages\sp_api\api\sales\sales.py", line 66, in get_order_metrics
    return self._request(kwargs.pop('path'), params=kwargs)
  File "C:\Users\DELL SERVER\PycharmProjects\ScrapeAE\venv\lib\site-packages\sp_api\base\client.py", line 125, in _request
    return self._check_response(res)
  File "C:\Users\DELL SERVER\PycharmProjects\ScrapeAE\venv\lib\site-packages\sp_api\base\client.py", line 140, in _check_response
    raise exception(error, headers=res.headers)
sp_api.base.exceptions.SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': '{getOrderMetrics.arg1=must match "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{3})?(([+-]\\d\\d:\\d\\d)|Z)(\\[[a-zA-Z/_]+\\])?--[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{3})?(([+-]\\d\\d:\\d\\d)|Z)(\\[[a-zA-Z/_]+\\])?"}', 'details': ''}]

**Comment by saleweaver** [comment]
Hi,

you have to pass dates in the correct format. However, you can simply use a tuple of `datetime`s:

````
from datetime import datetime, timedelta, timezone

import pytz

from sp_api.api import Sales
from sp_api.base import Granularity

tz = pytz.timezone('US/Central')
fmt = '%Y-%m-%dT%H:%M:%S%z'

interval = (datetime.now(tz) - timedelta(days=185)), (datetime.now(tz))


def test_sales_granularity_total():
    res = Sales().get_order_metrics(interval, Granularity.TOTAL, granularityTimeZone='US/Central')
    assert res.payload[0].get('unitCount') == 2


def test_sales_granularity_day():
    res = Sales().get_order_metrics(interval, Granularity.DAY, granularityTimeZone='US/Central')
    assert res.payload[0].get('unitCount') == 1


def test_sales_granularity_total_by_asin():
    res = Sales().get_order_metrics(interval, Granularity.TOTAL, granularityTimeZone='US/Central', asin='B008OLKVEW')
    assert res.payload[0].get('unitCount') == 1


def test_sales_granularity_day_by_asin():
    res = Sales().get_order_metrics(interval, Granularity.DAY, granularityTimeZone='US/Central', asin='B008OLKVEW')
    assert res.payload[0].get('unitCount') == 1


`````

**Comment by AnsonHwang86** [comment]
Hello, I don't understand why I pass dates in correct format still get the errors? thanks

**Comment by AnsonHwang86** [comment]
![image](https://user-images.githubusercontent.com/16233397/150717430-190397a2-87f6-4300-a99c-e2306ee05e99.png)
`https://github.com/saleweaver/selling-partner-api-docs/blob/main/references/sales-api/sales.md`
Hello, the doc state that can accept string as parameter. I check there is correct in date string format expecting lack of granularityTimeZone, I add it and test again, still get the same error.
