### ISSUE TITLE
get_product_fees_estimate_for_asin endpoint multi currency crash

### ISSUE THREAD

**Issue by demrebicer** [saleweaver/python-amazon-sp-api#355]
We are unable to submit the marketplace_id for endpoint "get_product_fees_estimate_for_asin". If we enter "MXN" as the currency, amazon returns an error because by default it searches the Americas marketplace, but to send "MXN" we have to set the marketplace to Mexico.

My Code

`    product_fee_response = ProductFees(credentials=credentials).get_product_fees_estimate_for_asin(
        marketplace_id=Marketplaces.MX.marketplace_id,
        asin=request.asin,
        price=1080,
        currency="MXN",
        is_fba=True,
    )`

Amazon Return

`{"FeesEstimateResult":{"Status":"ClientError","FeesEstimateIdentifier":{"MarketplaceId":"ATVPDKIKX0DER","IdType":"ASIN",`

Result:

I send MX marketplace_id but amazon return US marketplace_id

**Comment by saleweaver** [comment]
Hi,

Can you please try to run with the marketplace passed to the client: `ProductFees(credentials=credentials, marketplace=Marketplaces.MX)`

**Comment by demrebicer** [comment]
> Hi,
> 
> Can you please try to run with the marketplace passed to the client:
> 
> ```
> ProductFees(credentials=credentials, marketplace=Marketplaces.MX)
> ```
I got this error. message
AttributeError: 'Marketplaces' object has no attribute 'region'

**Comment by saleweaver** [comment]
That's quite unlikely if you're using `Marketplaces` from `sp_api.base`. I've added a commit that allows to pass a marketplace_id as a parameter to the method. Please check out v0.12.3 in a couple of minutes. 
However, I'd suggest to use `ProductFees(marketplace=Marketplaces.MX, credentials=credentials)

**Comment by demrebicer** [comment]
I'm sorry The auto import, import Marketplaces from mws. I changed it to sp_api.base and my problem was fixed. Thanks.
