### ISSUE TITLE
Module not Found Error in v0.12.3

### ISSUE THREAD

**Issue by ANarayanan-Cervello** [saleweaver/python-amazon-sp-api#356]
Hi Team,
             I was trying to work with the latest version of the Saleweaver API, when I ran into a ModuleNotFound error.
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12732/613414556.py in <module>
----> 1 from __version__ import __version__ as version

ModuleNotFoundError: No module named '__version__'

----------------------------------------------------------------------------
```

Upon inspecting the code(with ref. to commit b9bed59) , I found that there has been a new import(__version__) in the sp_api/base/base_client.py file.
However, the file __version__.py in present in the root package(/__version__.py) looks fine. 
Again, I didn't face any issue with v 0.12.2 ,and since the former is a recent addition, could you please have a look?

Regards,

**Comment by saleweaver** [comment]
Thanks! This should be fixed now, please use https://github.com/saleweaver/python-amazon-sp-api/releases/tag/v0.12.4
