### ISSUE TITLE
KeyError: 'endpoint_resolver'

### ISSUE THREAD

**Issue by demrebicer** [saleweaver/python-amazon-sp-api#360]
I got an error sometimes while using multiprocessing. I tried to run 5 times for testing 4 of it I got this error. 1 of it no problem.

Traceback (most recent call last):
  File "cencored/file/path", line 129, in processing
    product_response = Catalog(
  File "/usr/local/lib/python3.9/site-packages/sp_api/base/client.py", line 39, in __init__
    self.boto3_client = boto3.client(
  File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 270, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 856, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 729, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 995, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'

**Comment by saleweaver** [comment]
Can you share some code please

**Comment by demrebicer** [comment]
I create a tester code for you. 

```
import gevent
from gevent import monkey
from gevent.threadpool import ThreadPool


# patches stdlib (including socket and ssl modules) to cooperate with other greenlets
monkey.patch_all()

from sp_api.api import Catalog
from sp_api.base import SellingApiException
import time


credentials = dict(
    refresh_token="cencored",
    lwa_app_id="cencored",
    lwa_client_secret="cencored",
    aws_access_key="cencored",
    aws_secret_key="cencored",
    role_arn="cencored",
)

def test():
    
    response = Catalog(credentials=credentials).list_items(UPC=['628136608138'])
    
    print(response())
        

pool = ThreadPool(6)

start = time.time()

jobs = [pool.spawn(test) for i in range(0, 100)]

gevent.wait(jobs)

end = time.time()

print("Total Elapsed Time: ", end - start)

```

**Comment by saleweaver** [comment]
Thanks, I'll have a look. The error seems to be this here: https://github.com/boto/boto3/issues/801

I've never used multiple threads for such an operation; the result will be a bunch of `SellingApiRequestThrottledException`s. Considering the low request volume Amazon allows, using multiple threads is not something I would spend a lot of time on.

**Comment by demrebicer** [comment]
Unfortunately, multiprocessing is a must to get more and faster data from amazon. pool = ThreadPool(6) I gave 6 here because amazon accepts 6 transactions per second. This way I don't experience any throttling. I edited the sample code so you don't experience Throttling. Do you think this problem can be solved?

Edited Code:

```
import gevent
from gevent import monkey
from gevent.threadpool import ThreadPool


# patches stdlib (including socket and ssl modules) to cooperate with other greenlets
monkey.patch_all()

from sp_api.api import Catalog
from sp_api.base import SellingApiException
import time


credentials = dict(
    refresh_token="cencored",
    lwa_app_id="cencored",
    lwa_client_secret="cencored",
    aws_access_key="cencored",
    aws_secret_key="cencored",
    role_arn="cencored",
)

def test():
    jobStart = time.time()

    response = Catalog(credentials=credentials).list_items(UPC=['628136608138'])
    
    print(response())

    # For throtling 1 second wait
    jobEnd = time.time()
    while jobEnd-jobStart < 1:
        jobEnd = time.time()
        time.sleep(0.1)
        

pool = ThreadPool(6)

start = time.time()

jobs = [pool.spawn(test) for i in range(0, 100)]

gevent.wait(jobs)

end = time.time()

print("Total Elapsed Time: ", end - start)



```

**Comment by saleweaver** [comment]
It already works, but `monkey.patch_all()` breaks it.

````

def run(client, sku):
    response = Catalog().list_items(MarketplaceId='TEST_CASE_200', SellerSKU=sku)
    print(response)
    return response()


def test_multi1():
    import gevent
    from gevent.threadpool import ThreadPool

    c = Catalog()
    pool = ThreadPool(6)
    jobs = [pool.spawn(run, c, 'SKU_200') for i in range(0, 100)]
    gevent.wait(jobs)

**Comment by demrebicer** [comment]
I remove monkey.patch_all() and pass the client. And the problem was fixed. Thank you so much.
