### ISSUE TITLE
Market Place from Token

### ISSUE THREAD

**Issue by mohamedfawzy96** [saleweaver/python-amazon-sp-api#37]
Do you think it would be possible to extract what marketplace he did choose while authorising from the user token ?

**Comment by saleweaver** [comment]
From the refresh token? I don't think so, but you could use the `sellers` endpoint to get the marketplaces a seller is registered in.

**Comment by mohamedfawzy96** [comment]
But when I use it this way:         
data = orders.get_orders(MarketPlaceIds=["ATVPDKIKX0DER", "A2EUQ1WTGCTBG2"])
I get InvalidSignature error so I assume I am doing something wrong ?

**Comment by saleweaver** [comment]
The parameter for marketplace ids is `MarketplaceIds`, but I assume you've spelled it wrong only here. I can't test right now, but I think this will be a missing conversion from array to string, can you try to `','.join(marketplaces)` and see if that works please?

**Comment by mohamedfawzy96** [comment]
Yes works with the join thanks !

**Comment by saleweaver** [comment]
Cool, I'll have to add that to a few endpoints, should be easier to call the orders endpoints.
