### ISSUE TITLE
Unable to get data back from Report API for returns Data.

### ISSUE THREAD

**Issue by pavneet9** [saleweaver/python-amazon-sp-api#379]
I am trying to make a call the reports API to get the reports for the past 7 days.

    d = datetime.today() - timedelta(days=7)
    d = d.strftime('%Y-%m-%dT%H:%M:%S.%fZ')
    today = datetime.today().strftime('%Y-%m-%dT%H:%M:%S.%fZ')

    res_returns = Reports(credentials=credentials, marketplace=Marketplaces.US).create_report(
        reportType=ReportType.GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE,
        dataStartTime= d
        )

The payload for this report creating comes without any error.

{'errors': None,
 'headers': {'Date': 'Tue, 08 Feb 2022 22:28:15 GMT', 'Content-Type': 'application/json', 'Content-Length': '39', 'Connection': 'keep-alive', 'x-amzn-RequestId': '90ead367-4e5e-46d3-a26a-91388c34ff58', 'x-amz-apigw-id': 'NPoz6GIboAMFacw=', 'X-Amzn-Trace-Id': 'Root=1-6202ee7f-11b1bcd64b0f762f6516109d'},
 'kwargs': {},
 'next_token': None,
 'pagination': None,
 'payload': {'reportId': '344013019031'},
 'rate_limit': None}

However when i check the status of the reports right away without any changes, I get the report as cancelled.

report = Reports(credentials=credentials, marketplace=Marketplaces.US).get_report('344013019031')
print(report)

{'errors': None,
 'headers': {'Date': 'Tue, 08 Feb 2022 22:31:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '382', 'Connection': 'keep-alive', 'x-amzn-RequestId': '87a1eec3-9ea3-41e0-8308-44c04417d1dc', 'x-amzn-RateLimit-Limit': '2.0', 'x-amz-apigw-id': 'NPpOsF2woAMFZmQ=', 'X-Amzn-Trace-Id': 'Root=1-6202ef2a-4ce52e5b262196a364cba0ac'},
 'kwargs': {},
 'next_token': None,
 'pagination': None,
 'payload': {'createdTime': '2022-02-08T22:28:15+00:00',
             'dataEndTime': '2022-02-08T22:28:15+00:00',
             'dataStartTime': '2022-01-25T15:28:13+00:00',
             'marketplaceIds': ['ATVPDKIKX0DER'],
             'processingEndTime': '2022-02-08T22:29:04+00:00',
             'processingStartTime': '2022-02-08T22:28:58+00:00',
             'processingStatus': 'CANCELLED',
             'reportId': '344013019031',
             'reportType': 'GET_XML_RETURNS_DATA_BY_RETURN_DATE'},
 'rate_limit': '2.0'}

I am sure there are returns in the time frame and my credentials also work. I want to get a flat of the returns data for the past 7 days.

**Comment by pavneet9** [comment]
Is this because there is a limit on how many reports we can request, because i face the same issue with reiumbrusement report as well, totally identical call to GET_FBA_REIMBURSEMENTS_DATA . In case of the report i get the status back as Fatal.

**Comment by saleweaver** [comment]
I've just tried it with different accounts. If there are returns, the report seems to get generated correctly.
