### ISSUE TITLE
create_feed silently fails when feed opened in text mode

### ISSUE THREAD

**Issue by gmweinberg** [saleweaver/python-amazon-sp-api#394]
### Discussed in https://github.com/saleweaver/python-amazon-sp-api/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **gmweinberg** February 16, 2022</sup>
I was having a hard time getting create_feed to work. Eventually I discovered you have to open the feed file in binary mode.

The code as it exists will silently fail if the file is opened in text mode.
The problem is thsi:
        try:
            upload_data = file.read().decode('iso-8859-1')
        except AttributeError:
            upload_data = file.read()

The "read" inside the try block will succeed, so when the  AttributeError: 'str' object has no attribute 'decode' is thrown, the second read comes up empty.

Here's my modified code:

        try:
            upload_data = file.read()
            upload_data = upload_data.decode('iso-8859-1')
        except AttributeError:
            pass

</div>

**Comment by saleweaver** [comment]
Thanks, I've missed that one! Can you create a PR with the modification? Otherwise I'll fix it tomorrow.
