### ISSUE TITLE
restrictedResources only works if not is an array

### ISSUE THREAD

**Issue by ximo1984** [saleweaver/python-amazon-sp-api#402]
**Describe the bug**
When I call create_restricted_data_token only works when restrictedResources is called like and object, not as array.

**To Reproduce**

This not works:
token_res = Tokens().create_restricted_data_token(restrictedResources=[{
     "method": "GET",
     "path": "/orders/v0/orders",
     "dataElements": ["buyerInfo", "shippingAddress"]
    }
])

This works:
token_res = Tokens().create_restricted_data_token(restrictedResources={
     "method": "GET",
     "path": "/orders/v0/orders",
     "dataElements": ["buyerInfo", "shippingAddress"]
    }
)

I don't know if it is a documentation mistake o a bug in the api.

**Comment by saleweaver** [comment]
Not sure what the mixup is here, but the code you've titled as working isn't working for me, and the code that passes an array as documented works. 

````
res = Tokens().create_restricted_data_token(restrictedResources=[
    {
        "method": "GET",
        "path": "/orders/v0/orders",
        "dataElements": ["buyerInfo", "shippingAddress"]
    }
])
print(res)
````

**Comment by saleweaver** [comment]
@ximo1984 does it work with the code provided?

**Comment by ximo1984** [comment]
For me only works when I call without array. Maybe it's because I don't have PII aproved and it's a amazon API Bug.

Thanks for the response.

**Comment by saleweaver** [comment]
You shouldn't get any successful response without PII access enabled?

**Comment by ximo1984** [comment]
I know, but I have a token response. But later when I try to use this token it doesn't work.

**Comment by gorskim** [comment]
@ximo1984 have you figured out the way to successfully use the token you retrieve?

**Comment by ximo1984** [comment]
@gorskim No, I haven't. Sorry.
Maybe it's a bug and it return a token but it doesn't work because I haven't passed PII.

**Comment by khanakia** [comment]
Getting error `[{'code': 'InvalidInput', 'message': 'Application do not have access to some or all requested resource', 'details': ''}]`

```
tokens_client = Tokens(credentials=credentials, marketplace=Marketplaces.IN)
tokenres = tokens_client.create_restricted_data_token(restrictedResources=[
     {
         "method": "GET",
         "path": "/orders/v0/orders/406-8719557-7575562",
     }
  ])
```

but when i pass as the object it works
```
tokenres = tokens_client.create_restricted_data_token(restrictedResources={
         "method": "GET",
         "path": "/orders/v0/orders/406-8719557-7575562",
     })
```

Any update ?

**Comment by ximo1984** [comment]
No updates, you have to pass PII to call this endpoint. I could not pass PII.
