### ISSUE TITLE
Access token is missing in the request header

### ISSUE THREAD

**Issue by jbnels** [saleweaver/python-amazon-sp-api#41]
This is my code:
```
from sp_api import api

credentials=dict(
        refresh_token='XXXXXX',
        lwa_app_id='XXXXXX',
        lwa_client_secret='XXXXXX',
        aws_secret_key='XXXXXX',
        aws_access_key='XXXXXX',
        role_arn='XXXXXX',
    )

response = api.Products(credentials=credentials).get_product_pricing_for_asins(asin_list="B08PTV374B")`
```

The only thing I can figure is that I'm using the wrong value somewhere.
I've verified all of the keys, tokens, and secrets several times:

refresh_token: I am using the refresh token given by selecting **Authorize** in the **Edit App** dropdown in developer central
lwa_app_id:  I have tried both the **App Id** next to the name of the app in developer central and **Client identifier** from the **LWA credentials** pop up.
lwa_client_secret: I'm using the **Client secret** from the **LWA credentials** pop up.
aws_secret_key: I'm using the secret key created during the IAM steps of the docs
aws_access_key: I'm using the access key created during the IAM steps of the docs.
role_arn:  I'm using the arn from the role created during the IAM steps of the docs.  

EDIT:

This is the response I'm getting:

```
(<class 'sp_api.base.exceptions.SellingApiForbiddenException'>, SellingApiForbiddenException([{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': 'Access token is missing in the request header.'}]), <traceback object at 0x7f21e94e4688>)
```

**Comment by saleweaver** [comment]
Can you try to call a marketplace you're registered in? The asin you posted doesn't exist in US as far as I see. You can pass a marketplace to the client `Products(marketplace=Marketplaces.UK, credentials...)`. Does this work?

**Comment by jbnels** [comment]
> Can you try to call a marketplace you're registered in? The asin you posted doesn't exist in US as far as I see. You can pass a marketplace to the client `Products(marketplace=Marketplaces.UK, credentials...)`. Does this work?

Passing Marketplaces.US results in an error for an undeclared variable.  Passing it in a string results in:
`(<class 'AttributeError'>, AttributeError("'str' object has no attribute 'endpoint'"), <traceback object at 0x7f3b9dc20308>)`

Do I pass the marketplace_id, as in **ATVPDKIKX0DER** for the united states?  Or do I pass the endpoint?

**Comment by saleweaver** [comment]
There can be many causes, if I remember correctly, the most probable is that the AWS acces key, secret key or role is wrong. I'm too tired today, if you haven't figured it out until then I'll have a look tomorrow in the morning.

**Comment by jbnels** [comment]
I'm still having no luck

**Comment by jbnels** [comment]
I have reverified the AWS access and secret keys, and the role is one I made going step by step in the docs
