### ISSUE TITLE
__init__() got an unexpected keyword argument 'credentials'

### ISSUE THREAD

**Issue by fkhjoy** [saleweaver/python-amazon-sp-api#42]
**Describe the bug**
When I run the sample code it's saying that an unexpected keyword argument credentials.
![image](https://user-images.githubusercontent.com/25137428/108175466-0072fb80-712b-11eb-9ee5-6aa73b713ded.png)

**To Reproduce**

`from datetime import datetime, timedelta`

`from sp_api.api import Orders`
`from sp_api.base import SellingApiException`

`credentials= dict(`
       ` refresh_token='Atzr|XXXXXXX',`
       ` lwa_app_id='amzn1.application-oa2-client.XXXXXXXX',`
        `lwa_client_secret='XXXXXXXXXX',`
        `aws_secret_key='XXXXXXXXXXXXX',`
        `aws_access_key='XXXXXXXXXXXX',`
        `role_arn='arn:aws:iam::XXXXXXXXX',`   
    `)`
`Orders(credentials=credentials).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())`
**Expected behavior**
I ran it yesterday and that was okay. 
But now running on different pc. I am getting this error

**Desktop (please complete the following information):**
Windows

**Additional context**
I installed the latest module using pip

**Comment by saleweaver** [comment]
Please check the version of the package you are using and update it.
