### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Zach-Snow** [saleweaver/python-amazon-sp-api#424]
I am calling the get_order endpoint like this,
`api_response = orders_api.get_orders(
                CreatedAfter=created_after,
                CreatedBefore=created_before,
                NextToken=next_token,
            )`
and it was working very well recently, but now when I call it, I get this error 
` File "/mnt/c/Users/ayubz/Documents/Amazing Brand/amazon-due-diligence/logic/get_orders.py", line 49, in get_orders
    api_response = orders_api.get_orders(
  File "/home/zakir/.local/lib/python3.8/site-packages/sp_api/base/helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "/home/zakir/.local/lib/python3.8/site-packages/sp_api/api/orders/orders.py", line 51, in get_orders
    return self._request(kwargs.pop('path'), params={**kwargs})
  File "/home/zakir/.local/lib/python3.8/site-packages/sp_api/base/client.py", line 114, in _request
    return self._check_response(res)
  File "/home/zakir/.local/lib/python3.8/site-packages/sp_api/base/client.py", line 118, in _check_response
    error = res.json().get('errors', None)
AttributeError: 'list' object has no attribute 'get'
`
Any idea why this might be happening?

**Comment by saleweaver** [comment]
Calling with next token and other parameters is at least not documented, can you try to make a documented call and report errors please.

**Comment by saleweaver** [comment]
Hm, it could actually be something else. Which version are you using?

**Comment by saleweaver** [comment]
Wow. Please update...

**Comment by saleweaver** [comment]
Are you sure it's 0.6?

**Comment by saleweaver** [comment]
Ah nice. I was worried that the next token could cause this. Good it's working!
