### ISSUE TITLE
RDT shortcut approach doesn't work for multi-page response

### ISSUE THREAD

**Issue by dannyrohde** [saleweaver/python-amazon-sp-api#425]
**Describe the bug**
When using the `Orders.get_order` call and handing through a `RestrictedResource` and getting a response that spans multiple pages, the RDT is only being used for the first page. This means that the first page will have the restricted data fields, but they will be silently dropped from all following pages in the same request (loaded via `next_token`).

The first page will take this branch in `sp_api/api/orders/orders.py.get_orders`:

```
if 'RestrictedResources' in kwargs:
   return self._access_restricted(kwargs)
```

and will get an RDT via:

```
self.restricted_data_token = token['restrictedDataToken']
r = self._request(kwargs.pop('original_path'), params={**kwargs})
self.restricted_data_token = None
```

but it will clear the RDT after the API call again. For the next page, there are no `RestrictedResources` in the kwargs, just the `next_token` and hence the call will be made without RDT (doesn't take the `if`branch, leading to the API to return the orders WITHOUT the restricted data:

```
return self._request(fill_query_params(kwargs.pop('path'), order_id), params={**kwargs}, add_marketplace=False)
```
There is no error message, this fails silently and can only be seen in the resulting data.

**To Reproduce**
Load a get_order request that spans multiple pages (more than 100 rows) and call it with the `@load_all_pages` decorator. Check the restricted data in the first page and subsequent pages. Use the shortcut call as outlined in the documentation.

```
orders = Orders().get_orders(
    RestrictedResources=['buyerInfo', 'shippingAddress'],
    LastUpdatedAfter=(datetime.utcnow() - timedelta(days=1)).isoformat()
)
```

**Expected behavior**

The RDT should carry through to all subsequent pages and these should also return the restricted data.

**Additional context**

Workaround is to manually get an RDT and to hand it over in the creation of the Order instance or set the restricted_data_token instance variable after instantiation.

```
Orders(restricted_data_token='<token>').get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
```

**Comment by chadsaun** [comment]
I can confirm this as it's doing it to me too.

**Comment by saleweaver** [comment]
Hi, can you try to remove the line where it removes the restricted token? (in the orders client)

**Comment by dannyrohde** [comment]
> Hi, can you try to remove the line where it removes the restricted token? (in the orders client)

My workaround is to add the token directly to the `Client` instance. 

Removing the line where it resets the RDT would be problematic when you use the same `Client`, calling multiple methods (e.g. first call the get_orders and then call the get_order_items). I think it would be better to track a `RestrictedResources` call and then go through the `if` branch here for the `next_token` requests:
```
        if 'RestrictedResources' in kwargs:
            kwargs.update({'original_path': fill_query_params(kwargs.get('path'), order_id)})
            return self._access_restricted(kwargs)
```

Not sure if it needs a change to `@load_all_pages` as well as I just had a long multi-page request and that failed after an hour as the RDT is only valid for an hour. I'm now tracking the expiry time as well and refresh when it's expired. Might be easier to catch the `SellingApiForbiddenException` deep in the code and refresh the RDT then retry.

Lastly, the Token API is quite throttled. That should be fine for `get_orders` but for `get_order_items` it came to a crawl. I had to call it upfront with a batch of 25 items (though SP-API documentation says 50). Though that might be difficult to implement in the library as you would need to know the Orders you call it on upfront.

**Comment by saleweaver** [comment]
Yes, that makes sense. I'm quite busy atm, but I hope to have time to take a look on the weekend. If you find something that works well, please comment or create a PR.

**Comment by dannyrohde** [comment]
> Yes, that makes sense. I'm quite busy atm, but I hope to have time to take a look on the weekend. If you find something that works well, please comment or create a PR 👍 .

Thanks for your efforts. Also wanted to say that I really appreciate the time and effort you put into this package. It really helps me a lot on my current project and I enjoy learning from reading the code.

I'll have a look at the debugger again and see if there's anything I can contribute to.

**Comment by saleweaver** [comment]
@chadsaun @dannyrohde I've pushed a little change to make this work, can you have a look if it works for you please. 
Usage is using `with`:

````
with Orders() as client:
    r = client.get_orders(RestrictedResources=['buyerInfo', 'shippingAddress'], LastUpdatedAfter=(datetime.now() - timedelta(days=30)).isoformat())
    log.info(r)
    x = client.get_orders(NextToken=r.next_token)
    log.info(x)
# no more restricted resources here.
log.info(client.get_orders(NextToken=r.next_token))

````

I think I'll change it to `with Orders(RestrictedResources=['buyerInfo', 'shippingAddress']) as client` - what do you think?

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/commit/e806506995a3b5c0a2d64cafdbfcbf321cd65bfd
