### ISSUE TITLE
KeyError: 'endpoint_resolver' when running api requests in multi thread

### ISSUE THREAD

**Issue by zonwizard** [saleweaver/python-amazon-sp-api#426]
**Describe the bug**
When initializing the `Sellers()` api in multiple threads the boto3 client gives sometimes the endpoint_resolver KeyError.

**To Reproduce**

call `Client().__init__()` in parallel threads

**Additional context**

[Add any other context about the problem here.]
As suggeste here  by [mhucka]
https://stackoverflow.com/questions/52675027/why-do-i-sometimes-get-key-error-using-sqs-client

this issue can be solved creating a separate boto3 session object in each thread

The following code has been tested and fixed the issue:

in sp_api.base.client.py

```
class Client(BaseClient):
.....
def __init__()
.....
      session = boto3.session.Session()
      self.boto3_client = session.client(
          'sts',
          aws_access_key_id=self.credentials.aws_access_key,
          aws_secret_access_key=self.credentials.aws_secret_key
      )
```

**Comment by saleweaver** [comment]
Weird, actually had it like that, no idea why this wasn't the online version. Here's the released version: https://github.com/saleweaver/python-amazon-sp-api/releases/tag/v0.13.7

**Comment by zonwizard** [comment]
Great!! Thanks a lot for the super quick fix
