### ISSUE TITLE
Access to request resource is denined

### ISSUE THREAD

**Issue by smilekudo** [saleweaver/python-amazon-sp-api#43]
Hi,
I got issue and don't know have i missed any steps?
`{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}`

Request
`import datetime`
`from sp_api import api`
`from sp_api import base`
`from sp_api import auth`
`credentials=dict(`
`        refresh_token='xxx',`
`        lwa_app_id='xxx',`
`        lwa_client_secret='xxx',`
`        aws_secret_key='xxx',`
`        aws_access_key='xxx',`
`        role_arn='xxx',`
`        )`
`createReportResponse = api.Reports(credentials=credentials).create_report(reportType='GET_FLAT_FILE_OPEN_LISTINGS_DATA')`

**Comment by saleweaver** [comment]
Hi,

I can confirm that the endpoint is working if called with correct and authorized credentials. It might help to contact Amazon regarding your access to resources, they're quite responsive to SP-API questions.
