### ISSUE TITLE
Feeds().get_feed_document() and Feeds().get_feed_result_document() have the same result

### ISSUE THREAD

**Issue by chadsaun** [saleweaver/python-amazon-sp-api#436]
I called these two functions...
```
Feeds().get_feed_document(doc_id)
Feeds().get_feed_result_document(doc_id)
```
...and I was expecting a different result for each one, but got the same result from both which was a string of XML.

According to the [docs](https://sp-api-docs.saleweaver.com/endpoints/feeds/) `get_feed_document()` should return an API Response

I'm using version `0.13.6`

**Comment by saleweaver** [comment]
Thanks for bringing this up, the documentation is wrong,  otherwise return the same response. 
Please have a look here : sp_api/api/feeds/feeds.py

I'll change the docs asap
