### ISSUE TITLE
Add proxy in the request with Requests

### ISSUE THREAD

**Issue by Camille-cmd** [saleweaver/python-amazon-sp-api#438]
**Which API - Endpoint is your request about.**

The use of proxies while making the request is needed.
In `client.py`, I propose to simply add it in `_request` method.

I have a pull request ready to be sent if you agree with this. 

Thank you.

**Comment by saleweaver** [comment]
Not sure if I can follow. Why is it needed? Can you create the PR and I'll have a look? Thanks!

**Comment by Camille-cmd** [comment]
Thank you ! We need a proxy to get outside from our internal network.
I have just created the PR. Thank you for your help !
