### ISSUE TITLE
Feeds get_feed_result_document method doesn't use correct encoding for JP market

### ISSUE THREAD

**Issue by rritoch** [saleweaver/python-amazon-sp-api#453]
**Describe the bug**
The get_feed_result_document() method doesn't provide parameters to override the encoding. The encoding is incorrect for Japanese reports which returns _shift_jis_ encoding.

**To Reproduce**

Submit a POST_FLAT_FILE_INVLOADER_DATA csv file to a Japanese marketplace (JP), optionally with errors. 

**Expected behavior**

A response should be returned with valid Japanese characters

**Desktop (please complete the following information):**

 - OS: [e.g. Linux/Mac/Windows]

Linux, Mac and WIndows

**Additional context**

**Comment by saleweaver** [comment]
Thanks for bringing this up, can you create a PR?
