### ISSUE TITLE
getListingsItem doesn't work if there are white spaces in SKU Param

### ISSUE THREAD

**Issue by DanielLanger** [saleweaver/python-amazon-sp-api#495]
When calling ListingItems.get_listing_item() passing in a SKU that contains whitespaces results in a NOT FOUND error. It seems like the whitespaces are being encoded/ encoded improperly? Can't fully tell what is causing the issue but it is returning

[{'code': 'NOT_FOUND', 'message': "SKU 'XXXX%20YYY%20ZZZ' not found in marketplace ATVPDKIKX0DER"}]

**Comment by PerfectWorld233** [comment]
you can replace the whitespaces with hyphen  for sku string

**Comment by DanielLanger** [comment]
hmmm, that doesn't seem to work either. just to confirm, you mean `-` character?

**Comment by DanielLanger** [comment]
Also running into the issue for skus with / in them. The error message for this case is [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}] though

I think this is an issue with amazon's API itself. unless there is a known replacement character for spaces and slashes

**Comment by abrihter** [comment]
@DanielLanger 
Think this is not related to SPAPI as we already had something similar 
I will try to check it out later in the night in order to confirm and should be able to update to solve for this one 

@saleweaver

**Comment by abrihter** [comment]
@saleweaver 
Tested this manually with other options also and look like you are correct @DanielLanger related to this could be on Amazon side as same behavior is present for other escaped chars (like `/`)

There is [thread](https://github.com/amzn/selling-partner-api-docs/discussions/2188) on SPAPI with similar issue posted few days ago and maybe that will resolve this issue

**Comment by DanielLanger** [comment]
Yup im following that thread too, thanks

**Comment by saleweaver** [comment]
@abrihter yes, think so too. Let's see how that goes, this has bugging me since day one

**Comment by DanielLanger** [comment]
fixed :) https://github.com/amzn/selling-partner-api-docs/issues/1656#issuecomment-1113788235

**Comment by abrihter** [comment]
@DanielLanger tnx :)
