### ISSUE TITLE
Credential should be scoped to a valid region

### ISSUE THREAD

**Issue by vincmarc** [saleweaver/python-amazon-sp-api#5]
Hi,

I tried to run 
this code:
try:
    res = Orders().get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
    print(res.payload)  # json data
except SellingApiException as ex:
    print(ex)

the error I get is [{'message': "Credential should be scoped to a valid region, not 'us-east-1'. ", 'code': 'InvalidSignature'}]
I also tried to change region but the error is the same:
[{'message':** "Credential should be scoped to a valid region, not 'eu-central-1'. ", 'code': 'InvalidSignature'}]

Can you help me?

**Comment by saleweaver** [comment]
The valid region for EU marketplaces is 'eu-west-1', see the [docs](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#Selling-Partner-API-endpoints).
If you want to call an EU marketplace, you'll also need to pass marketplace to Orders:

```
Orders(marketplace=Marketplaces.DE).get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
```

Does that work for you?

**Comment by vincmarc** [comment]
It worked! Thanks!
