### ISSUE TITLE
Pagination issue CatalogItems with search_catalog_items

### ISSUE THREAD

**Issue by jasonsnare** [saleweaver/python-amazon-sp-api#522]
**Issue**
Response initially shows 13921 results. When I begin to paginate the response only includes a next_token for the first 740 products

**To Reproduce**
params: keywords=['GSP'], brandNames=['GSP']

 - OS: Mac

**Comment by saleweaver** [comment]
The client doesn't alter the response from Amazon in any way, it may be worth to open the issue in Amazon's repository for the sp-api instead.
