### ISSUE TITLE
TaxCollection missing

### ISSUE THREAD

**Issue by alesconti** [saleweaver/python-amazon-sp-api#53]
I have an order from the UK marketplace in which I am sure there should be information relating to the TaxCollection, but I don't understand why I cannot read it in the "get_order_items" call.

**Comment by saleweaver** [comment]
I don't think I can do something about that, the response is returned unaltered. I know that there was no tax information included for nun US orders in the past, I don't know the current state on this. 

If you need reliable financial information, you should use the finances api endpoint.

**Comment by alesconti** [comment]
Ok thanks I will search a solution
