### ISSUE TITLE
feed data error AttributeError: 'str' object has no attribute 'read'

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#54]
`feeds.Feeds(marketplace=Marketplaces.US,credentials=credentials).submit_feed(feed_type='str' ,file='SKU-12345\tLyric 500 tc Queen Flat Sheet, Ivory\t17.8\t50\tnew', content_type='text/tsv')`
or i am calling with xml file
`feeds.Feeds(marketplace=Marketplaces.US,credentials=credentials).submit_feed(feed_type='str' ,file='feed.txt', content_type='text/tsv')`
and my xml file is
[feed.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6029517/feed.txt)

in both of the calling function i am getting same error

**Comment by saleweaver** [comment]
You need to pass a file object, not a string. 

file=open('feed.txt')
