### ISSUE TITLE
Incorrect rate limit

### ISSUE THREAD

**Issue by discover59** [saleweaver/python-amazon-sp-api#542]
https://github.com/saleweaver/python-amazon-sp-api/blob/2ebd4bee86e8ea4081920991bafdc2c137e3b6e7/sp_api/api/inventories/inventories.py#L29

This line has incorrect rate limit.

It should be 2 and 2.

**Comment by saleweaver** [comment]
Thanks, can you create a PR or should I ?

**Comment by saleweaver** [comment]
Thank you!

**Comment by discover59** [comment]
> Thank you!

Thank you!
