### ISSUE TITLE
Getting feed data error 

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#55]
thank you soo much brother u help me a lot
please help me in shorting this out 
why i am getting this error while uploading the feed data my calling function
`Feeds(marketplace=Marketplaces.US,credentials=credentials).submit_feed(feed_type='str' ,file=open('feed2.txt'), content_type='text/tsv')`
i am getting this error
`[{'code': 'InvalidInput', 'message': "1 validation error detected: Value '[]' at 'marketplaceIdList' failed to satisfy constraint: Member must have length greater than or equal to 1", 'details': ''}]`
is my feed data formate is right? if u please give me an example of feeds data file than it help me a lot
[feed.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6029643/feed.txt)
[feed2.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6029645/feed2.txt)

**Comment by saleweaver** [comment]
It seems like they have changed something about how they read the marketplace. For the moment, you can pip install from the latest version of this repository (not from pip), then your call should work again.
