### ISSUE TITLE
AccessTokenResponse Cache is cleared with every new access token request

### ISSUE THREAD

**Issue by zonwizard** [saleweaver/python-amazon-sp-api#560]
**Describe the bug**
At every new access toke request the cache is reinitialized.
So the cache will never contain more than one cached authorization token.

auth.access_token_client.py 
class AccessTokenClient

```
def get_auth(self) -> AccessTokenResponse:
        """
        Get's the access token
        :return:AccessTokenResponse
        """
        global cache

        cache_key = self._get_cache_key()
        try:
            access_token = cache[cache_key]
        except KeyError:
            cache_ttl = 3600
            access_token = None
            if not access_token:
                request_url = self.scheme + self.host + self.path
                access_token = self._request(request_url, self.data, self.headers)
            else:
                cache_ttl = access_token.get('expires_in')
            cache = TTLCache(maxsize=10, ttl=cache_ttl - 15)  # <---- THE CACHE IS CLEARED HERE
            cache[cache_key] = access_token
        return AccessTokenResponse(**access_token)
```

**Expected behavior**
The cache should be initialized only once and be updated when a new access token is requested.

**Additional context**
In addition to this issue, it would also be very useful to be able to set the TTLCache maxsize to a value greater than 10 since we usually cycle through more than 10 authorizations.
This applies to :

auth.access_token_client.py 
```
cache = TTLCache(maxsize=10, ttl=3600)
grantless_cache = TTLCache(maxsize=10, ttl=3600)
```
base.client.py
`role_cache = TTLCache(maxsize=1000, ttl=3600)`

A good solution in my opinion would be to have the maxsize as an environmental variable or 10 by default.

Thanks

**Comment by saleweaver** [comment]
Thanks, I'll have a look!

**Comment by zonwizard** [comment]
Hi Michael, this is great!! 
Can you add the SP_API_AUTH_CACHE_SIZE also to the role_cache in the base.client.py?

Thanks a lot for your awesome work.

**Comment by zonwizard** [comment]
Hey Michael, if you are going to improve the cache system, it might be a good idea also to reduce the TTL.
Since 3600 seconds is the exact expiration time for the tokens it might happen that after finding a token in the cache it expires before he actual API request is made.
{'message': 'The security token included in the request is expired', 'code': 'Unauthorized'}

Thanks
