### ISSUE TITLE
Error On Request

### ISSUE THREAD

**Issue by nawaf-sheikh-qbatch** [saleweaver/python-amazon-sp-api#58]
I'm receiving an error 

[{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': 'Access token is missing in the request header.'}]

on any request I make (checked on getMarketPlaceParticipation and getOrders). And there is no method to pass an access_token.

**Comment by saleweaver** [comment]
Hi,

please follow Amazon's Getting Started guide closely on how to setup your credentials. 

If the error persists, please contact Amazon to troubleshoot your credentials and access to their API.
