### ISSUE TITLE
Support APIs with JSON array response.

### ISSUE THREAD

**Issue by discover59** [saleweaver/python-amazon-sp-api#582]
https://github.com/saleweaver/python-amazon-sp-api/blob/5e8bc529e245256fedf89913ead8ba76ba67918f/sp_api/base/client.py#L142

Some APIs return array of JSON objects. With above line, the module cannot return whole array.

**Comment by saleweaver** [comment]
Which endpoint doesn't return the whole response?

**Comment by discover59** [comment]
One of ProductFee endpoints returns array data.
https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference#post-productsfeesv0feesestimate

https://github.com/amzn/selling-partner-api-models/blob/2e8a5022040bec71ca0d67507b0c92087d82d42d/models/product-fees-api-model/productFeesV0.json#L549

**Comment by saleweaver** [comment]
Ok, thanks. Both of the endpoints seem to return correct data. I don't think that this issue is valid - can you please reopen it, should you find an endpoint that returns invalid data. 
Thanks!

**Comment by discover59** [comment]
@saleweaver Is this repository supports the endpoint? Did you check with bulk products?

**Comment by discover59** [comment]
Please reopen this issue. If you add this endpoint, you'll get the json array response and only first json will be returned.

**Comment by saleweaver** [comment]
I have no idea what you mean. Can you elaborate please? What are bulk products in ProductFees?

**Comment by saleweaver** [comment]
This one: GetMyFeesEstimateRequest ?

**Comment by discover59** [comment]
You can request fee data for multiple products at a time.
If seller has thousands of products, it's better to request with bundle of products instead of requesting one by one.

This is the purpose of endpoint `/products/fees/v0/feesEstimate`.

**Comment by discover59** [comment]
`GetMyFeesEstimateRequest` is for single product.
`GetMyFeesEstimatesRequest` is for bulk products.

**Comment by saleweaver** [comment]
Ok. Can you please send a request you made that gave this error. @discover59

**Comment by discover59** [comment]
Since there is no function for this case, I created custom request function and it returned only one product data.
data parameter is changed from dict to list.

```
def _request_new(self, path: str, *, data: list, params: dict = None, headers=None,
             res_no_data: bool = False) -> ApiResponse:
    self.method = "POST"
    res = request(self.method, self.endpoint + path,
                  params=params,
                  data=json.dumps(data) if data else None,
                  headers=headers or self.headers,
                  auth=self._sign_request(),
                  proxies=self.proxies)
    return self._check_response(res, res_no_data)
```

**Comment by saleweaver** [comment]
Ok, this looks like my own code. I'll take some time later to create the request myself - I'm quite busy atm, might be the weekend. Still - if you want to help, please send me your request to make this faster.

**Comment by discover59** [comment]
To keep it in the queue, would you reopen the issue?

**Comment by discover59** [comment]
```
products = [
    {"id_type": "SellerSKU", "id_value": "ABC", "price": 14.99, "is_fba": True, "currency": "USD", "identifier": "ABC", "marketplace_id": "ATVPDKIKX0DER"},
    {"id_type": "SellerSKU", "id_value": "ABD", "price": 17.99, "is_fba": True, "currency": "USD", "identifier": "ABD", "marketplace_id": "ATVPDKIKX0DER"},
]
res = client.get_bulk_product_fees(data=products)
```

**Comment by saleweaver** [comment]
@discover59 Thanks, that helps. I'll have a look

**Comment by discover59** [comment]
Thank you, @saleweaver

**Comment by saleweaver** [comment]
@discover59 You're actually right btw - there are two new bulk endpoints that now start to return data differently.... I'll add this shortly.
