### ISSUE TITLE
Feed api error [{'code': 'InvalidInput', 'message': 'feed type _str_ is invalid', 'details': ''}]

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#59]
getting error in feed api
feeds.Feeds(marketplace=Marketplaces.US,credentials=credentials).submit_feed(feed_type='str' ,file=open('feed2.txt'), content_type='text/tsv')
uploading the file 
[feed3.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6034299/feed3.txt)
[feed.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6034300/feed.txt)
[feed2.txt](https://github.com/saleweaver/python-amazon-sp-api/files/6034301/feed2.txt)
among above three feed file which one is correctly configured and also can u please give me the format of feed data file can be very helpful

**Comment by saleweaver** [comment]
Hi,

please follow the documentation, why are you passing 'str' as a feed type? You have to tell Amazon what type of feed you're sending, not that your file contains a string.
