### ISSUE TITLE
Geeting error from sample code. Need clear documentation to run that at least.

### ISSUE THREAD

**Issue by fkhjoy** [saleweaver/python-amazon-sp-api#6]
**Describe the bug**
When I run the sample code in the readme.md, it doesn't succeed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saleweaver** [comment]
From the credentials you have leaked I can see that you've set the wrong parameters. Please set the correct credentials as persistent env variables like shown in the readme. Your lwa app id is not your access key.

**Comment by fkhjoy** [comment]
> From the credentials you have leaked I can see that you've set the wrong parameters. Please set the correct credentials as persistent env variables like shown in the readme. Your lwa app id is not your access key.

So, I have to set all the environment variables in the readme?

**Comment by saleweaver** [comment]
Exactly, yes.

**Comment by fkhjoy** [comment]
Thanks.
I am checking it.
Please don't close the comment section.
I may contribute to the documentation section after doing some experimentation.
Do you have any suggestions for documentation?

**Comment by saleweaver** [comment]
That would be really cool! To be honest, I haven't thought about documentation too much, but I agree that it should be improved. Can you come back with ideas after you've experimented ?

**Comment by saleweaver** [comment]
I've removed the image, please consider changing your credentials :-)

**Comment by fkhjoy** [comment]
> I've removed the image, please consider changing your credentials :-)

I added new image.
Okay. I will change.
Will come back after some experimentation.

**Comment by fkhjoy** [comment]
Hi.
![Screenshot from 2021-01-27 23-24-03](https://user-images.githubusercontent.com/25137428/106029040-e24f4800-60f6-11eb-92c9-1d2caf3925b6.png)
Getting this error.
I Set all the variables as.
Don't know why getting error.
I would be grateful, if you could at least add the variables set up in the readme

**Comment by saleweaver** [comment]
You have to set environment variables from the cli with export ... ...
Am 27. Jan. 2021, 18:59 +0100 schrieb Foysal Khandakar Joy <notifications@github.com>:


Hi.

Getting this error.
I Set all the variables as.
Don't know why getting error.
I would be grateful, if you could at least add the variables set up in the readme

**Comment by fkhjoy** [comment]
> set environment variables from the cli with export

I am not getting how to do that.
Sorry for that,
Could you please help? 
I didn't find any proper article

**Comment by fkhjoy** [comment]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set

Is it?

**Comment by saleweaver** [comment]
Yes. Just replace the variables with what's in my readme. :-)

```
export SP_API_REFRESH_TOKEN="...."
export LWA_APP_ID="..."
...
```

**Comment by fkhjoy** [comment]
![Screenshot from 2021-01-28 01-53-22](https://user-images.githubusercontent.com/25137428/106045816-a96d9e00-610b-11eb-98f4-5072b9bdcf0c.png)

I did it on terminal. Still getting this error.
Is there any documentation about setting those export LWA_APP_ID="..." ?

**Comment by saleweaver** [comment]
Did you set the all the values from the readme? It looks like you didn't.
I can help you setting up the correct roles, users and permissions, my hourly rate is $80; I'm working through upwork. 
Please send me a request via email and we can go on from there, the setup usually takes around 30-45 minutes.

**Comment by fkhjoy** [comment]
> Did you set the all the values from the readme? It looks like you didn't.
> I can help you setting up the correct roles, users and permissions, my hourly rate is $80; I'm working through upwork.
> Please send me a request via email and we can go on from there, the setup usually takes around 30-45 minutes.

I didn't set the refresh token though.
Share your mail. We can discuss

**Comment by saleweaver** [comment]
info@saleweaver.com
