### ISSUE TITLE
SyntaxError: client.py", line 101

### ISSUE THREAD

**Issue by alesconti** [saleweaver/python-amazon-sp-api#7]
o.s: Debian
python rel: 3.5

Code to reproduce the errore:
""""""""
from datetime import datetime, timedelta

from sp_api.api import Orders
from sp_api.base import SellingApiException

try:
    res = Orders().get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=1)).isoformat())
    print(res.payload)  # json data
except SellingApiException as ex:
    print(ex)

"""""""""""

**Comment by alesconti** [comment]
Found the solution by myself.
I need Python 3.8 !

**Comment by saleweaver** [comment]
Yes. I should change the line though, it's the only line that uses that syntax. Thanks for highlighting this... :-)

**Comment by mohamedfawzy96** [comment]
is this line still there or was it changed ?

**Comment by saleweaver** [comment]
@mohamedfawzy96 I've removed it, python 3.5 is supported after the change

**Comment by mohamedfawzy96** [comment]
okay thank you so much !
