### ISSUE TITLE
Type hint on product_fees only valid on Python >= 3.9

### ISSUE THREAD

**Issue by Lars147** [saleweaver/python-amazon-sp-api#701]
**Which API - Endpoint is your request about.**

The type hint `list[dict]` on https://github.com/saleweaver/python-amazon-sp-api/blob/2e831a278dded226f5242df0c18eeec05e48ac78/sp_api/api/product_fees/product_fees.py#L99

is only valid for Python >= 3.9

I could not find a supported Python version on the documentation. Hence, it would be great if you still support Python 3.8 by changing that line to 

```pyhton
from typing import List
...
 def get_product_fees_estimate(self, estimate_requests: List[dict]) -> ApiResponse: 
```

Because you are still import the typing module on other endpoint, I think this is not a major break in continuity. Only an advantage to still support Python 3.8

Please let me know if I should create a PR for this. Cheers

**Comment by saleweaver** [comment]
Hi, a PR would be great

**Comment by DanielLanger** [comment]
+1, this broke when upgrading

**Comment by Lars147** [comment]
> Hi, a PR would be great

Alright. Will create PR today
