### ISSUE TITLE
Inventory API not working...

### ISSUE THREAD

**Issue by kstar0101** [saleweaver/python-amazon-sp-api#72]
I'm requesting by following code.
`
        inventoryClient = api.Inventories(credentials=self.credentials, marketplace=Marketplaces.JP)
`
`
        res = inventoryClient.get_inventory_summary_marketplace(sellerSkus=['sku1', 'sku2'])
`
Then I'm getting error.
> sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

However my credentials is correct.
Other API(feed, report...) is working.
Please help me.

**Comment by kevincojean** [comment]
In the app registration form, you'll need to have the inventory box ticked

![2021-03-01 15_43_32-Window](https://user-images.githubusercontent.com/40899632/109513021-fa730800-7aa4-11eb-8378-4c7601cb5ab6.png)

**Comment by kstar0101** [comment]
> In the app registration form, in sellercentral, you'll need to have the inventory box ticked.
> 
> ![2021-03-01 15_43_32-Window](https://user-images.githubusercontent.com/40899632/109513021-fa730800-7aa4-11eb-8378-4c7601cb5ab6.png)

Thanks for answer.
But I'm already check it.

**Comment by saleweaver** [comment]
Can you try to add `marketplaceIds=[Marketplaces.JP.marketplace_id]` to the request please.

**Comment by kstar0101** [comment]
> Can you try to add `marketplaceIds=[Marketplaces.JP.marketplace_id]` to the request please.

Thanks saleweaver.
I just tried
But I still get the error.

**Comment by saleweaver** [comment]
Yeah, just wanted to check if you might be using an old version. Your best bet is to contact Amazon and ask them what the problem with your credentials/client app is.

**Comment by sjenriquez** [comment]
@saleweaver I had the same issue and was able to resolve by adding `marketplaceIds=[Marketplaces.US.marketplace_id]` to the request.

In your last reply you suggested that addition
> to check if you might be using an old version. 

Can you give more details about this? I'm using `0.5.2` which I believe is the latest. 

Thanks!

**Comment by saleweaver** [comment]
@sjenriquez Which endpoint are you using? The comments in this thread are unrelated to your issue, but it'll be a quick fix

**Comment by sjenriquez** [comment]
@saleweaver This was for the [/fba/inventory/v1/summaries](https://github.com/saleweaver/python-amazon-sp-api/blob/master/sp_api/api/inventories/inventories.py#L12) endpoint used in the `Inventories` class. The successful call looked like:

```
res = Inventories(marketplace=Marketplaces.US, credentials=credentials).get_inventory_summary_marketplace(marketplaceIds=[Marketplaces.US.marketplace_id])
```
