### ISSUE TITLE
[BREAKING] Version of `python-amazon-sp-api` on PyPI needs to be updated

### ISSUE THREAD

**Issue by spelsbergsam** [saleweaver/python-amazon-sp-api#728]
### Discussed in https://github.com/saleweaver/python-amazon-sp-api/discussions/727

<div type='discussions-op-text'>

<sup>Originally posted by **spelsbergsam** September  7, 2022</sup>
Hi, 

I am working with this incredible library right now and I wanted to point out that the code version that gets pulled by `pip` does not include the change made 7 days ago in `product_fees.py` to change `list[dict]` to `List[dict]`, and so any invocation of the library fails with this error:
```
  File "/Users/samuel/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sp_api/api/product_fees/product_fees.py", line 99, in ProductFees
    def get_product_fees_estimate(self, estimate_requests: list[dict]) -> ApiResponse:
TypeError: 'type' object is not subscriptable
```

I was able to go into the source code and make the change myself, but I cannot put this in a Docker container or anywhere where it needs to function out of the box right now. 

I see the code already exists in the repo, just not in the version that we can pull from `pip`. **Could we please make a hotfix release to allow `pip` to grab the fixed code?** </div>

**Comment by saleweaver** [comment]
Hi, will release later

**Comment by saleweaver** [comment]
https://github.com/saleweaver/python-amazon-sp-api/releases/tag/v0.17.1
