### ISSUE TITLE
Bug on notifications

### ISSUE THREAD

**Issue by crax0** [saleweaver/python-amazon-sp-api#734]
If i try to create a subscription for the FEED_PROCESSING_FINISHED notification i get the error message:
sp_api.base.exceptions.SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': 'Request has missing or invalid parameters and cannot be parsed.', 'details': 'Notification type FEED_PROCESSING_FINISHED does not support AWS_EVENT_BRIDGE'}]

Why is FEED_PROCESSING_FINISHED not supported by the AWS Event Bridge? Am i forgetting something here?

This is my code:
`def create_subscription_event():
    notification = Notifications(marketplace=Marketplaces.DE, credentials=credentials)
    destination = notification.create_destination("FeedNotifiactionTest", account_id="XXX", arn="arn:aws:sqs:eu-central-1:XXX:queue1")
    destination_id = destination.payload["destinationId"]
    # print(destination_id)
    subscription = notification.create_subscription(notification_type=NotificationType.FEED_PROCESSING_FINISHED, destination_id=destination_id)
    # print(subscription)`

**Comment by saleweaver** [comment]
Check the docs, it clearly states that only sqs is supported for this notification type
