### ISSUE TITLE
getListingOffersBatch not implemented

### ISSUE THREAD

**Issue by DanielLanger** [saleweaver/python-amazon-sp-api#735]
**Which API - Endpoint is your request about.**

https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getlistingoffersbatch

Can this new endpoint be implemented? I see getItemOffersBatch (https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getitemoffersbatch) was implemented, but not the getListingOffersBatch endpoint.

**Comment by saleweaver** [comment]
Hi, will try to do some stuff on the weekend

**Comment by MILORDY** [comment]
Hello,
Has it already been implemented?
Thanks in advance
@DanielLanger @saleweaver

**Comment by anykeyjunkie** [comment]
As of now, looks like still not implemented unfortunately. Maybe will be in the future... Thanks for the library anyway!

**Comment by saleweaver** [comment]
> As of now, looks like still not implemented unfortunately. Maybe will be in the future... Thanks for the library anyway!

You do understand this is an open source library, right? Please create a PR and I'm happy to merge. Thanks anyway!
