### ISSUE TITLE
Question: Should different approach be used if application is registered with User ARN?

### ISSUE THREAD

**Issue by wolendranh** [saleweaver/python-amazon-sp-api#74]
Hi! 
So basically, my question is in summary. 
I have application that was registered with User ARN. Should different approach be used if application is registered with User ARN?
Can I still use this package? Thx!

**Comment by saleweaver** [comment]
TBH I don't know if you can use Amazon's selling partner api at all with a wrong setup. I'd consider using the setup as described in Amazon's documentation instead.

**Comment by wolendranh** [comment]
@saleweaver thx for answer. Btw I created new APP with Role ARN, and it worked well. 
Maybe this will help somebody. Always use ROLE ARN, not USER ARN when registering application. 
Though documentation [states](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application) that you can use both: 

> Important. When registering your application, the IAM ARN that you provide must be for the IAM entity to which you attached the IAM policy from Step 3. Create an IAM policy. In this workflow, that IAM entity is the IAM role from Step 4. Create an IAM role. **If you register your application using your IAM user, be sure that the IAM policy is attached to it**. Otherwise your calls to the Selling Partner API will fail. We recommend registering your application using an IAM role, as shown in this workflow, to help you better control access to your AWS resources.

**Comment by saleweaver** [comment]
Ah ok, interesting. I thought it was plain wrong, but seems to be possible then. Most of the documentation explains the role based approach, I think that part of the documentation is confusing a lot of people and most of the auth. errors will come from this misconception. 

I'd almost always attach policies to roles.
