### ISSUE TITLE
Japanese reports require different encoding when getting the document and saving it

### ISSUE THREAD

**Issue by RobertAbaev** [saleweaver/python-amazon-sp-api#769]
**Describe the bug**
While working with Reports API in Japanese marketplace I stumbled upon a bug where you get invalid output characters when getting data from provided URL. Method **get_report_document**

**To Reproduce**

There are actually several cases I want to highlight.

**First** - download as is:
1. Just try downloading and saving report from Japanese marketplace with default character encoding settings (**iso-8859-1**). 
2. This works without issues but produces invalid character in output file. Something like this: 
> White Paint Pen �z���C�g �y�C���g�y��

**Second** - download as **utf-8**:
1. Try downloading and saving report from Japanese marketplace with **utf-8** character encoding settings. 
2. If report contains Japanese character, the program will fail. Decoding line will produce an error like this:
```
UnicodeDecodeError                        Traceback (most recent call last)
Cell In [63], line 3
      1 document = res.content
      2 # decoded = document.decode('cp932')
----> 3 decoded = document.decode('utf-8')
      4 decoded

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 537: invalid start byte
```

**Third** - download as **cp932**:
1. Try downloading and saving report from Japanese marketplace with **cp932** character encoding settings. 
2. This works without issues but again produces invalid character in output file (like in the first case). That happens because right now it is programmed to try to encode output file with the same encoding that it was downloaded with (so **cp932** in this case). But this just produces invalid characters. Although when I tried saving **cp932** encoded document as **utf-8** encoded file separately and it produced desired result.

**Expected behavior**

The report file with Japanese character gets saved properly.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Python 3.9.13

**Additional context**

I actually don't know if it's a Python issue, but I have a suggestion on how to patch it.
**get_report_document** could get two different encoding arguments: one for document decoding (`document_character_code`) and one for file (`file_character_code`). This will allow for more flexibility while working with different marketplaces (and you never know what **Amazon SP-API** team will come up with next).

Also I'm afraid I can't share much of my output data and don't really know how to reproduce it without our credentials. If there are some open credentials for Japanese market I will be willing to expand my bug report. Also I'm open to fixing this issue myself if it is possible.

**Comment by RobertAbaev** [comment]
Actually, I played around with document call and looked through other PRs, and it looks like what @madp suggested in his #764  should be implemented here as well

**Comment by saleweaver** [comment]
Hey guys, I'm not really available the next few days. I've merged the PR - please checkout from master and check if it works for you!

**Comment by rmanganiello** [comment]
We have made the Reports client smarter, now, it will deduce the encoding to use by checking the `Content-Encoding` header from the Document response while downloading it.

Check this PR for more information:
https://github.com/saleweaver/python-amazon-sp-api/pull/844

We're waiting for a new release 😀
