### ISSUE TITLE
get_competitive_pricing_for_skus : Required parameter SellerSKU not found

### ISSUE THREAD

**Issue by alesconti** [saleweaver/python-amazon-sp-api#77]
I try to use get_competitive_pricing_for_skus call but I receive the error
[{'message': 'Required parameter SellerSKU not found', 'code': 'InvalidInput', 'details': ''}]

My call example:
res = Products(
                        credentials=credentials,
                        marketplace=mkt
                    ).get_competitive_pricing_for_skus(
                        seller_sku_list=[
                            'LA-19411',
                        ]
                    )

**Comment by saleweaver** [comment]
Hi Alessandro, I can't reproduce this, running your code works for me. If you haven't done already, please update to the latest version and try again; I can't remember a version where this particular call did not work though.
