### ISSUE TITLE
JSONDecodeError when getting Bad Request (400) response from API

### ISSUE THREAD

**Issue by michip89** [saleweaver/python-amazon-sp-api#811]
**Describe the bug**

When I make a call to _/products/fees/v0/listings/Some_SKU/feesEstimate_ via _get_product_fees_estimate_for_sku_ with a SKU containing a space, the API can't handle the call (I think there is still no workaround) and answers with a 400 response with no content, so in  

    def _check_response(self, res) -> ApiResponse:
        if self.method == 'DELETE' and 200 <= res.status_code < 300:
            try:
                js = res.json() or {}
            except JSONDecodeError:
                js = {'status_code': res.status_code}
        else:
            js = res.json() or {}

in the else branch a JSONDecodeError is thrown. 

Is there any need for the if / else ? Why not always catch the Exception?

**Comment by rmanganiello** [comment]
This was solved in https://github.com/saleweaver/python-amazon-sp-api/pull/845

We're waiting for a release 😃

**Comment by saleweaver** [comment]
Really sorry, totally forgot. @rmanganiello 😀

Released now
