### ISSUE TITLE
Fulfillment Outbound

### ISSUE THREAD

**Issue by ritik-novostack** [saleweaver/python-amazon-sp-api#85]
when u will create Class of this endpoint api?
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md

**Comment by saleweaver** [comment]
Hi. 
I have no plans for this API at the moment and a lot to do with other projects. It will come, but I can't say when. 
Feel free to create a pull request with the endpoint and I'll happily merge it.
