### ISSUE TITLE
Dict type object has no attribute 'lwa_app_id' when implementing OAuth

### ISSUE THREAD

**Issue by earthcomfy** [saleweaver/python-amazon-sp-api#852]
I was trying to implement OAuth using the `AccessTokenClient` class. 

I put my credentials in a dictionary like these:
```
credentials = dict(
     lwa_app_id=settings.LWA_APP_ID,
     lwa_client_secret=settings.LWA_CLIENT_SECRET,
)
```
Then I called `AccessTokenClient(credentials=credentials).authorize_auth_code(auth_code)`. However, I get the following error:

**dict type has no attribute lwa_app_id**

And when passing no credentials, I get the following error:

**NoneType object has no attribute lwa_app_id**

I checked the [Credentials](https://github.com/saleweaver/python-amazon-sp-api/blob/master/sp_api/auth/credentials.py) class of the package class to see what data type it is expecting and found this:

```
class Credentials:
    def __init__(self, refresh_token, credentials):
        self.client_id = credentials.lwa_app_id
        self.client_secret = credentials.lwa_client_secret
        self.refresh_token = refresh_token or credentials.refresh_token
```
It is trying to access the credentials with the dot operator

and this is the access token client class:
```
class AccessTokenClient(BaseClient):
    host = 'api.amazon.com'
    grant_type = 'refresh_token'
    path = '/auth/o2/token'

    def __init__(self, refresh_token=None, credentials=None, proxies=None, verify=True):
        self.cred = Credentials(refresh_token, credentials)
        self.proxies = proxies
        self.verify = verify
```

So, whether or not I pass credentials it won't work. Shouldn't the Credentials class be accessing the values like a dictionary using the get operator instead of dot? or am I missing something here? Thanks.

**Comment by saleweaver** [comment]
That's a bug, please use the access token client like this:

    res = AccessTokenClient(credentials=CredentialProvider().credentials).authorize_auth_code(auth_code)

**Comment by earthcomfy** [comment]
> That's a bug, please use the access token client like this:
> 
> ```
> res = AccessTokenClient(credentials=CredentialProvider().credentials).authorize_auth_code(auth_code)
> ```
> 
> I'm not at the computer, if you're using security credentials in code instead of one of the secure options, you need to pass the duct to credentialProvider.

Ok, thank you so much for the quick response. Will try that.

**Comment by earthcomfy** [comment]
@saleweaver I can work on a fix for this bug and send a PR

**Comment by saleweaver** [comment]
That would be awesome. I think checking if it's a CredentialsProvider instance in AccessTokenClient should be enough already.

**Comment by cnr91** [comment]
I have installed `"python-amazon-sp-api 0.18.0"` the latest version now, but I am getting the same error.
