### ISSUE TITLE
No estimated-ltsf-next-charge-6-month column in GET_FBA_INVENTORY_PLANNING_DATA report

### ISSUE THREAD

**Issue by mercivboku** [saleweaver/python-amazon-sp-api#862]
**Describe the bug**
There are `estimated-ltsf-next-charge-6-month` and `estimated-ltsf-next-charge-12-month` columns  in the [documentation](https://sellercentral.amazon.com/help/hub/reference/GKT9YKCHXMSDVJKB) of GET_FBA_INVENTORY_PLANNING_DATA report. But there is only `estimated-ltsf-next-charge` column without detalization in the downloaded report. 

**To Reproduce**
Go to interface and download the report or use API to download GET_FBA_INVENTORY_PLANNING_DATA report.

 - OS: MacOS Monterey

**Comment by saleweaver** [comment]
Hey, can you report this to Amazon instead please. Thanks!
