### ISSUE TITLE
SellingApiServerException - while call - create_product_review_and_seller_feedback_solicitation api in sandbox env

### ISSUE THREAD

**Issue by Lokeesh-27** [saleweaver/python-amazon-sp-api#943]
`
from sp_api.api import Solicitations
`
`
from sp_api.base import Marketplaces
`

`
credentials=dict(
        refresh_token='your_refresh_token',
        lwa_app_id='your_lwa_app_id',
        lwa_client_secret='your_lwa_client_secret',
        aws_secret_key='your_aws_secret_key',
        aws_access_key='your_aws_access_key',
        role_arn='your_role_arn'
    )
`

`
if __name__ == "__main__":
`
`     solicitation = Solicitations(credentials=credentials,  marketplace=Marketplaces.US)`
`      solicitation_api = solicitation.create_product_review_and_seller_feedback_solicitation(amazonOrderId='123-1234567-1234567', marketplaceIds = [Marketplaces.US.marketplace_id]
)
`

This is my response for create_product_review_and_seller_feedback_solicitation -
`sp_api.base.exceptions.SellingApiServerException: [{'message': 'We encountered an internal error. Please try again.', 'code': 'InternalFailure'}]`

I have pass all the credentials currently and it is `working with get_solicitation_actions_for_order API` but it is `causing problem for create_product_review_and_seller_feedback_solicitation API`.

**Comment by yberezkin** [comment]
@Lokeesh-27,
Did you try to run `get_solicitation_actions_for_order` before `create_product_review_and_seller_feedback_solicitation`?
Could you check if it's available for order? also - when was the order created, if it was too long ago - it won't be available.

**Comment by Lokeesh-27** [comment]
> @Lokeesh-27, Did you try to run `get_solicitation_actions_for_order` before `create_product_review_and_seller_feedback_solicitation`? Could you check if it's available for order? also - when was the order created, if it was too long ago - it won't be available.

This is my `get_solicitation_actions_for_order` API response and this is `SandBox Environment` -

`{`
`    "_links": {`
`        "actions": [`
`            {`
`                "href": "/solicitations/v1/orders/123-1234567-1234567/solicitations/productReviewAndSellerFeedback?marketplaceIds=ATVPDKIKX0DER",`
`                "name": "productReviewAndSellerFeedback"`
`            }`
`        ],`
 `       "self": {`
`            "href": "/solicitations/v1/orders/123-1234567-1234567?marketplaceIds=ATVPDKIKX0DER"`
`        }`
`    }`
`}`

after running `get_solicitation_actions_for_order` only i am running `create_product_review_and_seller_feedback_solicitation` -

This is the error facing after running create_product_review_and_seller_feedback_solicitation` API -

`sp_api.base.exceptions.SellingApiServerException: [{'message': 'We encountered an internal error. Please try again.', 'code': 'InternalFailure'}]`

**Comment by yberezkin** [comment]
@Lokeesh-27 
Sorry for long response.

I am not sure this will work in SandBox (assuming it should)

But in my prod code, I use simple logic:

```python3
amz_order_id = 'SomeAmazonOrderId'
r = cli.get_solicitation_actions_for_order(amazonOrderId= amz_order_id)
actions = resp.payload.get('_links', {}).get('actions', [])
act_ = next((e for e in actions if e.get('name', '') == 'productReviewAndSellerFeedback'), None)
if act_:
    response = cli.create_product_review_and_seller_feedback_solicitation(
        amazonOrderId= amz_order_id, marketplaceIds='ATVPDKIKX0DER')  # or marketplace_id for your order
```

**Comment by Lokeesh-27** [comment]
@yberezkin 

I think this is a problem from Amazon side while using sandbox env. Thanks for the assist man.
