### ISSUE TITLE
Error retrieve price for items with "/" or blank in the sky

### ISSUE THREAD

**Issue by alesconti** [saleweaver/python-amazon-sp-api#96]
I try to get listing offer for some items with blank space or / in sku

res = Products(
                    credentials=credentials,
                    marketplace=mkt
                ).get_listing_offers(
                    seller_sku= "MS-S6-35036/WH" ,
                    ItemCondition = 'New',
                )

I receive error "Access to requested resource is denied."

**Comment by saleweaver** [comment]
I've rejected the pull request, there was an error in it. I'll add the working method later the week.
